import type { SiteReportTemplateDefinition } from './types';

const doorFields = [
  { id: 'door_location', label: 'Door location', type: 'text' as const },
  { id: 'fire_door_rating', label: 'Fire door rating (e.g. FD30, FD60)', type: 'text' as const },
  { id: 'door_location_photos', label: 'Door location photos', type: 'image' as const },
  { id: 'third_party_label', label: 'Does the door have a third party scheme label / plug?', type: 'yes_no_na' as const },
  { id: 'certification_status', label: 'Certification status (e.g. nominal fire door)', type: 'text' as const },
  { id: 'construction_material', label: 'Door construction material', type: 'text' as const },
  { id: 'frame_stop_damage', label: 'Is the door frame and stop free from damage?', type: 'yes_no_na' as const },
  { id: 'leaf_damage', label: 'Is the door leaf free from damage?', type: 'yes_no_na' as const },
  { id: 'has_vision_panel', label: 'Is there a vision panel in the fire door?', type: 'yes_no_na' as const },
  { id: 'vision_panel_damage', label: 'Is the vision panel free from damage and fire rated?', type: 'yes_no_na' as const },
  { id: 'has_letterbox', label: 'Does the fire door have a letterbox?', type: 'yes_no_na' as const },
  { id: 'lock_adequate', label: 'Is the fire door lock mechanism adequate and free from damage?', type: 'yes_no_na' as const },
  { id: 'correct_signage', label: 'Does the fire door have the correct signage?', type: 'yes_no_na' as const },
  { id: 'defect_photos_frame_leaf', label: 'Photos of any defects in the door stop, frame or leaf', type: 'image' as const },
  { id: 'gap_left_mm', label: 'Gaps on the left side of the fire door (mm)', type: 'text' as const },
  { id: 'gap_right_mm', label: 'Gaps on the right side of the fire door (mm)', type: 'text' as const },
  { id: 'gap_top_mm', label: 'Gaps along the top of the fire door (mm)', type: 'text' as const },
  { id: 'gap_bottom_mm', label: 'Gap under the bottom of the fire door (mm)', type: 'text' as const },
  { id: 'gaps_adequate', label: 'Are the gaps between the fire door and frame found to be adequate?', type: 'yes_no_na' as const },
  { id: 'gap_photos', label: 'Photos around the fire door', type: 'image' as const },
  { id: 'intumescent_seals_in_place', label: 'Are intumescent strips and cold smoke seals in place?', type: 'yes_no_na' as const },
  { id: 'seals_location', label: 'Where are intumescent strips / cold smoke seals found? (door frame, door leaf, etc.)', type: 'textarea' as const, rows: 3 },
  { id: 'seals_damage_free', label: 'Are the intumescent strips and cold smoke seals free from damage?', type: 'yes_no_na' as const },
  { id: 'seal_damage_photos', label: 'Photos of any damage to intumescent seals or cold smoke seals', type: 'image' as const },
  { id: 'three_grade11_hinges', label: 'Are there three grade 11 fire rated hinges fitted to the fire door?', type: 'yes_no_na' as const },
  { id: 'hinges_damage_free', label: 'Are the hinges free from any damage?', type: 'yes_no_na' as const },
  { id: 'hinges_properly_fitted', label: 'Are the hinges properly fitted?', type: 'yes_no_na' as const },
  { id: 'hinge_photos', label: 'Photos of the hinges', type: 'image' as const },
  { id: 'door_closer_attached', label: 'Does the fire door have a door closer adequately attached?', type: 'yes_no_na' as const },
  { id: 'door_closer_type', label: 'What type of door closer is found on the fire door?', type: 'text' as const },
  { id: 'door_closer_closes_flush', label: 'Does the door closer close the door flush against the frame when left to do so?', type: 'yes_no_na' as const },
  { id: 'door_closer_photo', label: 'Door closer photo', type: 'image' as const },
  { id: 'hold_open_device', label: 'Does the fire door have a hold open device attached?', type: 'yes_no_na' as const },
  { id: 'hold_open_releases', label: 'Does the hold open device release the fire door when required to do so?', type: 'yes_no_na' as const },
  { id: 'hold_open_photo', label: 'Photo of the hold open device attached to the fire door', type: 'image' as const },
  { id: 'non_conformity_components', label: 'Non-conformity components', type: 'textarea' as const, rows: 4 },
  { id: 'remedial_action_required', label: 'Remedial action required?', type: 'yes_no_na' as const },
  { id: 'remedial_recommendations', label: 'Remedial action recommendations', type: 'textarea' as const, rows: 4 },
  { id: 'door_pass_fail', label: 'Pass or fail?', type: 'pass_fail' as const },
];

export function getFireDoorSurveyDefinition(): SiteReportTemplateDefinition {
  return {
    version: 1,
    report_title_default: 'Fire Door Survey',
    sections: [
      {
        id: 'site_summary',
        title: 'Site / job summary',
        helper_text: 'Overall site and visit details for this fire door survey.',
        fields: [
          { id: 'location_number', label: 'Location number', type: 'text' },
          { id: 'location_description', label: 'Location description', type: 'text' },
          { id: 'block', label: 'Block', type: 'text' },
          { id: 'level', label: 'Level', type: 'text' },
          { id: 'site_pass_fail', label: 'Overall pass or fail?', type: 'pass_fail' },
          { id: 'job_sheet_number', label: 'Job sheet number', type: 'text' },
          { id: 'survey_timestamp', label: 'Survey timestamp', type: 'text' },
        ],
      },
      {
        id: 'fire_doors',
        title: 'Fire doors',
        helper_text: 'Add one entry for each fire door surveyed on this site. Large sites may have many doors.',
        repeatable: true,
        repeat_label: 'Door',
        add_label: 'Add door',
        fields: doorFields,
      },
    ],
    footer: {
      title: 'Operative',
      fields: [
        { id: 'operative_name', label: 'Operative', type: 'text' },
        { id: 'operative_qualifications', label: 'Qualifications', type: 'textarea', rows: 3 },
        { id: 'operative_signature', label: 'Operative signature', type: 'signature' },
      ],
      allow_section_images: false,
    },
  };
}
