export interface InspectionScheduleItem {
  id: string;
  section: string;
  label: string;
}

export const INSPECTION_SCHEDULE_ITEMS: InspectionScheduleItem[] = [
  { id: '1.1', section: '1', label: 'Intake equipment - service cable, service head, earthing arrangement, meter tails, metering equipment, isolator (where present)' },
  { id: '1.1.1', section: '1', label: 'Person ordering work / duty holder notified' },
  { id: '1.2', section: '1', label: "Consumer's isolator (where present)" },
  { id: '1.3', section: '1', label: "Consumer's meter tails" },
  { id: '2.0', section: '2', label: 'Presence of adequate arrangements for other sources such as microgenerators (551.6; 551.7)' },
  { id: '3.1', section: '3', label: "Presence and condition of distributor's earthing arrangements (542.1.2.1; 542.1.2.2)" },
  { id: '3.2', section: '3', label: 'Presence and condition of earth electrode connection where applicable (542.1.2.3)' },
  { id: '3.3', section: '3', label: 'Provision of earthing/bonding labels at all appropriate locations (514.13.1)' },
  { id: '3.4', section: '3', label: 'Confirmation of earthing conductor size (542.3; 543.1.1)' },
  { id: '3.5', section: '3', label: 'Accessibility and condition of earthing conductor at MET (543.3.2)' },
  { id: '3.6', section: '3', label: 'Confirmation of main protective bonding conductor sizes (544.1)' },
  { id: '3.7', section: '3', label: 'Condition and accessibility of main protective bonding conductor connections (543.3.2; 544.1.2)' },
  { id: '3.8', section: '3', label: 'Accessibility and condition of other protective bonding connections (543.3.1; 543.3.2)' },
  { id: '4.1', section: '4', label: 'Adequacy of working space/accessibility to consumer unit/distribution board (132.12; 513.1)' },
  { id: '4.2', section: '4', label: 'Security of fixing (134.1.1)' },
  { id: '4.3', section: '4', label: 'Condition of enclosure(s) in terms of IP rating etc (416.2)' },
  { id: '4.4', section: '4', label: 'Condition of enclosure(s) in terms of fire rating etc (421.1.201; 526.5)' },
  { id: '4.5', section: '4', label: 'Enclosure not damaged/deteriorated so as to impair safety (651.2)' },
  { id: '4.6', section: '4', label: 'Presence of main linked switched (as required by 462.1.201)' },
  { id: '4.7', section: '4', label: 'Operation of main switch (functional check) (643.10)' },
  { id: '4.8', section: '4', label: 'Manual operation of circuit breakers and RCDs to prove disconnection (643.10)' },
  { id: '4.9', section: '4', label: 'Correct identification of circuit details and protective devices (514.8.1; 514.9.1)' },
  { id: '4.10', section: '4', label: 'Presence of RCD six-monthly test notice at or near consumer unit/distribution board (514.12.2)' },
  { id: '4.11', section: '4', label: 'Presence of alternative supply warning notice at or near consumer unit/distribution board (514.15)' },
  { id: '4.12', section: '4', label: 'Presence of other required labelling (please specify) (Section 514)' },
  { id: '4.13', section: '4', label: 'Compatibility of protective devices, bases and other components, correct type and rating (No signs of unacceptable thermal damage, arcing or overheating) (411.3.2; 411.4; 411.5; 411.6; Sections 432, 433)' },
  { id: '4.14', section: '4', label: 'Single-pole switching or protective devices in line conductor only (132.14.1; 530.3.3)' },
  { id: '4.15', section: '4', label: 'Protection against mechanical damage where cables enter consumer unit/distribution board (522.8.1; 522.8.5; 522.8.11)' },
  { id: '4.16', section: '4', label: 'Protection against electromagnetic effects where cables enter consumer unit/distribution board/enclosures (521.5.1)' },
  { id: '4.17', section: '4', label: 'RCD(s) provided for fault protection - includes RCBOs (411.4.204; 411.5.2; 531.2)' },
  { id: '4.18', section: '4', label: 'RCD(s) provided for additional protection / requirements - includes RCBOs (411.3.3; 415.1)' },
  { id: '4.19', section: '4', label: 'Confirmation of indication that SPD is functional (651.4)' },
  { id: '4.20', section: '4', label: 'Confirmation that ALL conductor connections, including connections to busbars, are correctly located in terminals and are tight and secure (526.1)' },
  { id: '4.21', section: '4', label: 'Adequate arrangements where a generating set operates as a switched alternative to the public supply (551.6)' },
  { id: '4.22', section: '4', label: 'Adequate arrangements where a generating set operates in parallel with the public supply (551.7)' },
  { id: '5.1', section: '5', label: 'Identification of conductors (514.3.1)' },
  { id: '5.2', section: '5', label: 'Cables correctly supported throughout their run (521.10.202; 522.8.5)' },
  { id: '5.3', section: '5', label: 'Condition of insulation of live parts (416.1)' },
  { id: '5.4', section: '5', label: 'Non sheathed cables protected by enclosure in conduit, ducting or trunking (521.10.1)' },
  { id: '5.4.1', section: '5', label: 'To include the integrity of conduit and trunking systems (metal and plastic)' },
  { id: '5.5', section: '5', label: 'Adequacy of cables for current carrying capacity with regard for the type and nature of installation (Section 523)' },
  { id: '5.6', section: '5', label: 'Coordination between conductors and overload protective devices (433.1; 533.2.1)' },
  { id: '5.7', section: '5', label: 'Adequacy of protective devices: type and rated current for fault protection (411.3)' },
  { id: '5.8', section: '5', label: 'Presence and adequacy of circuit protective conductors (411.3.1; Section 543)' },
  { id: '5.9', section: '5', label: 'Wiring system(s) appropriate for the type and nature of the installation and external influences (Section 522)' },
  { id: '5.10', section: '5', label: 'Concealed cables installed in prescribed zones (see Extent and limitations) (522.6.202)' },
  { id: '5.11', section: '5', label: 'Cables concealed under floors, above ceilings or in walls/partitions, adequately protected against damage (see Extent and limitations) (522.6.204)' },
  { id: '5.12', section: '5', label: 'Provision of additional requirements for protection by RCD not exceeding 30 mA' },
  { id: '5.12.1', section: '5', label: 'For all socket outlets of rating 32A or less, unless an exception is permitted (411.3.3)' },
  { id: '5.12.2', section: '5', label: 'For the supply of mobile equipment not exceeding 32A rating for use outdoors' },
  { id: '5.12.3', section: '5', label: 'For cables concealed in walls at a depth of less than 50mm (522.6.202; 522.6.203)' },
  { id: '5.12.4', section: '5', label: 'For final circuits supplying luminaires within domestic (household) premises (411.3.4)' },
  { id: '5.13', section: '5', label: 'Provision of fire barriers, sealing arrangements and protection against thermal effects (Section 527)' },
  { id: '5.14', section: '5', label: 'Band II cables segregated/separated from Band I cables (528.1)' },
  { id: '5.15', section: '5', label: 'Cables segregated/separated from communications cabling (528.2)' },
  { id: '5.16', section: '5', label: 'Cables segregated/separated from non-electrical services (528.3)' },
  { id: '5.17', section: '5', label: 'Termination of cables at enclosures - indicate extent of sampling in Extent of Limitations of the report (Section 526)' },
  { id: '5.17.1', section: '5', label: 'Connections soundly made and under no undue strain (526.6)' },
  { id: '5.17.2', section: '5', label: 'No basic insulation of a conductor visible outside enclosure (526.8)' },
  { id: '5.17.3', section: '5', label: 'Connections of live conductors adequately enclosed (526.5)' },
  { id: '5.17.4', section: '5', label: 'Adequately connected at point of entry to enclosure (glands, bushes etc.) (522.8.5)' },
  { id: '5.18', section: '5', label: 'Condition of accessories including socket-outlets, switches and joint boxes (651.2 (v))' },
  { id: '5.19', section: '5', label: 'Suitability of accessories for external influences (512.2)' },
  { id: '5.20', section: '5', label: 'Adequacy of working space/accessibility to equipment (132.12; 513.1)' },
  { id: '5.21', section: '5', label: 'Single-pole switching or protective devices in line conductors only (132.14.1; 530.3.3)' },
  { id: '6.1', section: '6', label: 'Additional protection for all low voltage (LV) circuits by RCD not exceeding 30mA (701.411.3.3)' },
  { id: '6.2', section: '6', label: 'Where used as a protective measure, requirements for SELV or PELV met (701.414.4.5)' },
  { id: '6.3', section: '6', label: 'Shaver sockets comply with BS EN 61558-2-5 formerly BS 3535 (701.512.3)' },
  { id: '6.4', section: '6', label: 'Presence of supplementary bonding conductors, unless not required by BS 7671:2018 (701.415.2)' },
  { id: '6.5', section: '6', label: 'Low voltage (e.g. 230 volt) socket-outlets sited at least 2.5m from zone (701.512.3)' },
  { id: '6.6', section: '6', label: 'Suitability of equipment for external influences for installed location in terms of IP rating (701.512.2)' },
  { id: '6.7', section: '6', label: 'Suitability of accessories and control-gear etc. for a particular zone (701.512.3)' },
  { id: '6.8', section: '6', label: 'Suitability of current using equipment for particular position within the location (701.55)' },
  { id: '7.02', section: '7', label: 'Swimming pools and other basins' },
  { id: '7.03', section: '7', label: 'Rooms and cabins containing sauna heaters' },
  { id: '7.04', section: '7', label: 'Construction and demolition site installations. (BS 7375 should also be consulted within this special location. Findings which contravene BS 7375 may need to be reported separately).' },
  { id: '7.05', section: '7', label: 'Agricultural and horticultural' },
  { id: '7.06', section: '7', label: 'Conducting locations with restricted movement' },
  { id: '7.08', section: '7', label: 'Electrical installations in caravan / camping parks and similar locations' },
  { id: '7.09', section: '7', label: 'Marinas and similar locations' },
  { id: '7.10', section: '7', label: 'Medical locations' },
  { id: '7.11', section: '7', label: 'Exhibitions, shows and stands. (BS 7909 should also be consulted within this special location. Findings which contravene BS 7909 may need to be reported separately).' },
  { id: '7.12', section: '7', label: 'Solar photovoltaic (PV) power supply systems' },
  { id: '7.14', section: '7', label: 'Outdoor lighting installations' },
  { id: '7.15', section: '7', label: 'Extra-low voltage lighting installations' },
  { id: '7.17', section: '7', label: 'Mobile or transportable units' },
  { id: '7.21', section: '7', label: 'Electrical installations in caravans and motor caravans' },
  { id: '7.22', section: '7', label: 'Electric vehicle charging installations' },
  { id: '7.29', section: '7', label: 'Operating and maintenance gangways' },
  { id: '7.30', section: '7', label: 'Onshore units of electrical connections for inland navigation vessels' },
  { id: '7.40', section: '7', label: 'Temporary electrical installations for structures, amusement devices and booths at fairgrounds, amusement parks and circuses. (BS 7909 should also be consulted within this special location. Findings which contravene BS 7909 may need to be reported separately).' },
  { id: '7.53', section: '7', label: 'Heating cables and embedded heating systems.' },
];

export const INSPECTION_SECTION_LABELS: Record<string, string> = {
  '1': 'External condition of intake equipment (visual inspection only)',
  '2': 'Presence of adequate arrangements for other sources such as microgenerators (551.6; 551.7)',
  '3': 'Earthing / bonding arrangements',
  '4': 'Consumer unit(s) / distribution board(s)',
  '5': 'Final circuits',
  '6': 'Location(s) containing a bath or shower',
  '7': 'Other Part 7 special installations or locations',
};
