class CircuitColSpec {
  const CircuitColSpec({
    required this.key,
    required this.label,
    this.calculated = false,
    this.group = '',
  });

  final String key;
  final String label;
  final bool calculated;
  final String group;
}

const Map<String, List<String>> circuitColumnOptions = {
  'description': ['Spare', 'Unknown'],
  'points': ['1', '2', '3', '4', '5', '6', '8', '10', '12', 'N/A', 'LIM'],
  'wiringType': ['A', 'B', 'C', 'D', 'SWA', 'MICC', 'FP200', 'Twin & earth', 'Singles', 'N/A', 'LIM', 'Other'],
  'refMethod': ['A1', 'A2', 'B1', 'B2', 'C', 'D', 'E', 'F', 'G', '100', '101', '102', '103', 'N/A', 'LIM'],
  'liveMm2': ['1', '1.5', '2.5', '4', '6', '10', '16', '25', '35', '50', '70', 'N/A', 'LIM'],
  'cpcMm2': ['1', '1.5', '2.5', '4', '6', '10', '16', '25', '35', 'N/A', 'LIM'],
  'maxDisconnectTime': ['0.2', '0.4', '1', '5', 'N/A', 'LIM'],
  'ocpdBs': ['60898', '61009', '88-2', '88-3', '3036', '3871', '1361', '60947-2', '60269', 'N/A', 'LIM', 'UNKNOWN'],
  'ocpdType': ['B', 'C', 'D', '1', '2', '3', 'gG', 'gL', 'aM', 'N/A', 'LIM'],
  'ocpdRatingA': ['5', '6', '10', '15', '16', '20', '25', '32', '40', '45', '50', '63', '80', '100', 'N/A', 'LIM'],
  'ocpdBreakingKa': ['1', '3', '6', '10', '16', '25', '33', '50', 'N/A', 'LIM', 'UNKNOWN'],
  'maxZs': ['N/A', 'LIM', 'N/V', '---'],
  'rcdBs': ['61008', '61009', '62423', 'N/A', 'LIM', 'UNKNOWN'],
  'rcdType': ['AC', 'A', 'F', 'B', 'S', 'N/A', 'LIM'],
  'rcdRatingMa': ['10', '30', '100', '300', '500', '1000', 'N/A', 'N/V', 'LIM'],
  'rcdRatingA': ['16', '20', '25', '32', '40', '63', '80', '100', 'N/A', 'LIM'],
  'ringR1': ['N/A', 'LIM', 'N/V', '---'],
  'ringRn': ['N/A', 'LIM', 'N/V', '---'],
  'ringR2End': ['N/A', 'LIM', 'N/V', '---'],
  'r1r2': ['N/A', 'LIM', 'N/V', '---'],
  'r2': ['N/A', 'LIM', 'N/V', '---'],
  'insulationTestVoltage': ['250', '500', '1000', 'N/A', 'LIM'],
  'insulationLL': ['>999', '>500', '>200', '>100', 'N/A', 'LIM', 'N/V', '---'],
  'insulationLE': ['>999', '>500', '>200', '>100', 'N/A', 'LIM', 'N/V', '---'],
  'polarity': ['PASS', 'FAIL', 'LIM', 'N/A'],
  'zs': ['N/A', 'LIM', 'N/V', '---'],
  'rcdTripMs': ['N/A', 'LIM', 'N/V', '---'],
  'afdd': ['PASS', 'FAIL', 'LIM', 'N/A'],
  'remarks': ['N/A', 'LIM', 'N/V', '---'],
};

const Map<String, double> circuitColWidths = {
  'actions': 96.0,
  'circuitNumber': 50.0,
  'description': 160.0,
  'points': 80.0,
  'wiringType': 100.0,
  'refMethod': 85.0,
  'liveMm2': 90.0,
  'cpcMm2': 90.0,
  'maxDisconnectTime': 90.0,
  'ocpdBs': 110.0,
  'ocpdType': 85.0,
  'ocpdRatingA': 90.0,
  'ocpdBreakingKa': 90.0,
  'maxZs': 85.0,
  'rcdBs': 110.0,
  'rcdType': 80.0,
  'rcdRatingMa': 80.0,
  'rcdRatingA': 80.0,
  'ringR1': 80.0,
  'ringRn': 80.0,
  'ringR2End': 80.0,
  'r1r2': 85.0,
  'r2': 80.0,
  'insulationTestVoltage': 100.0,
  'insulationLL': 80.0,
  'insulationLE': 80.0,
  'polarity': 80.0,
  'zs': 85.0,
  'rcdTripMs': 80.0,
  'afdd': 80.0,
  'remarks': 180.0,
};

const Map<String, String> circuitGroupLabels = {
  'conductors': 'Conductors',
  'ocpd': 'Overcurrent devices',
  'rcd': 'RCD',
  'ring': 'Ring final',
  'insulation': 'Insulation',
  'tests': 'Tests',
};

const List<CircuitColSpec> CIRCUIT_COLUMNS_SPEC = [
  CircuitColSpec(key: 'actions', label: 'Actions'),
  CircuitColSpec(key: 'circuitNumber', label: '#'),
  CircuitColSpec(key: 'description', label: 'Circuit description'),
  CircuitColSpec(key: 'points', label: 'No. points'),
  CircuitColSpec(key: 'wiringType', label: 'Wiring type', group: 'conductors'),
  CircuitColSpec(key: 'refMethod', label: 'Ref method', group: 'conductors'),
  CircuitColSpec(key: 'liveMm2', label: 'Live mm²', group: 'conductors'),
  CircuitColSpec(key: 'cpcMm2', label: 'cpc mm²', calculated: true, group: 'conductors'),
  CircuitColSpec(key: 'maxDisconnectTime', label: 'Max disconnect time (s)', calculated: true, group: 'ocpd'),
  CircuitColSpec(key: 'ocpdBs', label: 'OCPD BS', group: 'ocpd'),
  CircuitColSpec(key: 'ocpdType', label: 'OCPD Type', group: 'ocpd'),
  CircuitColSpec(key: 'ocpdRatingA', label: 'Rating (A)', group: 'ocpd'),
  CircuitColSpec(key: 'ocpdBreakingKa', label: 'Breaking (kA)', calculated: true, group: 'ocpd'),
  CircuitColSpec(key: 'maxZs', label: 'Max Zs (Ω)', calculated: true, group: 'ocpd'),
  CircuitColSpec(key: 'rcdBs', label: 'RCD BS', group: 'rcd'),
  CircuitColSpec(key: 'rcdType', label: 'RCD Type', group: 'rcd'),
  CircuitColSpec(key: 'rcdRatingMa', label: 'IΔn (mA)', group: 'rcd'),
  CircuitColSpec(key: 'rcdRatingA', label: 'RCD Rating (A)', group: 'rcd'),
  CircuitColSpec(key: 'ringR1', label: 'r1 (Ω)', group: 'ring'),
  CircuitColSpec(key: 'ringRn', label: 'rn (Ω)', group: 'ring'),
  CircuitColSpec(key: 'ringR2End', label: 'r2 (Ω)', group: 'ring'),
  CircuitColSpec(key: 'r1r2', label: 'R1+R2 (Ω)', calculated: true, group: 'ring'),
  CircuitColSpec(key: 'r2', label: 'R2 (Ω)', group: 'ring'),
  CircuitColSpec(key: 'insulationTestVoltage', label: 'Test voltage (V)', group: 'insulation'),
  CircuitColSpec(key: 'insulationLL', label: 'L-L (MΩ)', group: 'insulation'),
  CircuitColSpec(key: 'insulationLE', label: 'L-E (MΩ)', group: 'insulation'),
  CircuitColSpec(key: 'polarity', label: 'Polarity', group: 'tests'),
  CircuitColSpec(key: 'zs', label: 'Measured Zs (Ω)', calculated: true, group: 'tests'),
  CircuitColSpec(key: 'rcdTripMs', label: 'RCD (ms)', group: 'tests'),
  CircuitColSpec(key: 'afdd', label: 'AFDD', group: 'tests'),
  CircuitColSpec(key: 'remarks', label: 'Remarks', group: 'tests'),
];
