import type { CompanyBranding } from './companyBranding';
import {
  DOMESTIC_FIRE_ALARM_CHECKLIST_ITEMS,
  DOMESTIC_FIRE_ALARM_CHECKLIST_OUTCOME_LABELS,
  DOMESTIC_FIRE_ALARM_CHECKLIST_SECTION_LABELS,
  DOMESTIC_FIRE_ALARM_REVISION,
  DOMESTIC_FIRE_ALARM_STANDARD,
} from './domesticFireAlarmItems';
import {
  FIRE_ALARM_INSPECTION_SCHEDULE_ITEMS,
  FIRE_ALARM_OUTCOME_LABELS,
  FIRE_ALARM_SECTION_LABELS,
} from './fireAlarmInspectionScheduleItems';
import { INSPECTION_SCHEDULE_ITEMS, INSPECTION_SECTION_LABELS } from './inspectionScheduleItems';
import type { ElectricalCertificateDocument, InspectionOutcome } from './types';

export type CertificatePdfInput = {
  certificateNumber: string;
  customerName: string | null;
  installationLabel: string | null;
  jobNumber: string | null;
  document: ElectricalCertificateDocument;
  branding: CompanyBranding;
};

const OUTCOME_LABELS: Record<InspectionOutcome, string> = {
  '': '—',
  pass: '✓',
  c1: 'C1',
  c2: 'C2',
  c3: 'C3',
  fi: 'FI',
  lim: 'LIM',
  nv: 'N/V',
  na: 'N/A',
  x: 'X',
};

function esc(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function row(label: string, value: string): string {
  if (!value.trim()) return '';
  return `<tr><td class="lbl">${esc(label)}</td><td>${esc(value)}</td></tr>`;
}

function photosHtml(photos: { caption: string; dataUrl: string }[], title: string): string {
  if (!photos.length) return '';
  const items = photos
    .map(
      (p) =>
        `<figure class="photo"><img src="${p.dataUrl}" alt="${esc(p.caption || 'Photo')}"/><figcaption>${esc(p.caption || '')}</figcaption></figure>`,
    )
    .join('');
  return `<section class="block"><h2>${esc(title)}</h2><div class="photos">${items}</div></section>`;
}

function certificateFooterHtml(branding: CompanyBranding, certificateNumber: string): string {
  const primary = branding.footer_text?.trim()
    || [branding.company_name.trim(), certificateNumber].filter(Boolean).join(' · ')
    || certificateNumber;
  return `<div class="footer"><span>${esc(primary)}</span><span class="generated-by">Generated by WorkPilot</span></div>`;
}

export function buildCertificatePdfHtml(input: CertificatePdfInput): string {
  const { document: doc, branding: b } = input;
  if (doc.typeSlug === 'portable_appliance_test') {
    return buildPatCertificatePdfHtml(input);
  }
  if (doc.typeSlug === 'fi_insp_2025') {
    return buildFireAlarmCertificatePdfHtml(input);
  }
  if (doc.typeSlug === 'dfi_insp_2019_a1') {
    return buildDomesticFireAlarmCertificatePdfHtml(input);
  }
  const inst = doc.installation;
  const sup = doc.supply;
  const accent = b.accent_color;
  const accentEnd = b.accent_end_color;

  const clientLine = inst.hideClientOnReport
    ? 'Client withheld on report'
    : esc(input.customerName ?? '—');

  const inspectionRows = [...new Set(INSPECTION_SCHEDULE_ITEMS.map((i) => i.section))]
    .map((sec) => {
      const items = INSPECTION_SCHEDULE_ITEMS.filter((i) => i.section === sec);
      const rows = items
        .map((item) => {
          const outcome = doc.inspectionSchedule[item.id] ?? '';
          return `<tr><td class="mono">${esc(item.id)}</td><td>${esc(item.label)}</td><td class="outcome">${esc(OUTCOME_LABELS[outcome] ?? outcome)}</td></tr>`;
        })
        .join('');
      return `<h3>${esc(sec)}. ${esc(INSPECTION_SECTION_LABELS[sec] ?? sec)}</h3><table class="sched"><thead><tr><th>Ref</th><th>Item</th><th>Outcome</th></tr></thead><tbody>${rows}</tbody></table>`;
    })
    .join('');

  const obsHtml =
    doc.observations.items.length > 0
      ? `<ul>${doc.observations.items
          .map(
            (o) =>
              `<li><strong>${esc(o.code.toUpperCase())}</strong> ${esc(o.location)}: ${esc(o.details)}</li>`,
          )
          .join('')}</ul>`
      : '<p class="muted">None recorded</p>';

  const boardsHtml = doc.boards
    .map((board) => {
      const boardPhotos =
        board.photos?.length > 0
          ? `<div class="photos">${board.photos
              .map(
                (p) =>
                  `<figure class="photo"><img src="${p.dataUrl}" alt=""/><figcaption>${esc(p.caption)}</figcaption></figure>`,
              )
              .join('')}</div>`
          : '';
      return `<div class="board"><h3>${esc(board.name)}</h3>
        <p class="muted">${board.circuits.length} circuits · ${board.status === 'done' ? 'Complete' : 'In progress'}${board.zsAtDb ? ` · Zdb ${esc(board.zsAtDb)} Ω` : ''}</p>
        ${boardPhotos}
      </div>`;
    })
    .join('');

  const appendixPhotos = doc.appendix.photos ?? [];

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>${esc(input.certificateNumber)} — EICR</title>
<style>
  @page { size: A4; margin: 14mm; }
  * { box-sizing: border-box; }
  body { font-family: system-ui, -apple-system, Segoe UI, sans-serif; font-size: 10pt; color: #0f172a; margin: 0; }
  .header { display: flex; gap: 16px; border-bottom: 3px solid ${accent}; padding-bottom: 12px; margin-bottom: 16px; }
  .logo { width: 72px; height: 72px; flex-shrink: 0; display: flex; align-items: center; justify-content: center; }
  .logo img { max-width: 100%; max-height: 100%; object-fit: contain; }
  .company h1 { margin: 0; font-size: 14pt; background: linear-gradient(90deg, ${accent}, ${accentEnd}); -webkit-background-clip: text; -webkit-text-fill-color: transparent; }
  .company p { margin: 2px 0 0; font-size: 9pt; color: #475569; }
  .cert-meta { margin-left: auto; text-align: right; font-size: 9pt; }
  .cert-meta strong { display: block; font-size: 12pt; color: #0f172a; }
  h2 { font-size: 11pt; margin: 16px 0 8px; padding-bottom: 4px; border-bottom: 1px solid #e2e8f0; }
  h3 { font-size: 10pt; margin: 12px 0 6px; color: #334155; }
  table.kv { width: 100%; border-collapse: collapse; margin-bottom: 8px; }
  table.kv td { padding: 3px 6px; vertical-align: top; border-bottom: 1px solid #f1f5f9; }
  table.kv td.lbl { width: 38%; color: #64748b; font-weight: 600; }
  table.sched { width: 100%; border-collapse: collapse; font-size: 8pt; margin-bottom: 12px; }
  table.sched th, table.sched td { border: 1px solid #cbd5e1; padding: 3px 5px; text-align: left; }
  table.sched th { background: #f8fafc; }
  table.sched td.mono { width: 36px; font-family: monospace; color: #64748b; }
  table.sched td.outcome { width: 48px; text-align: center; font-weight: 700; }
  .muted { color: #64748b; font-size: 9pt; }
  .board { margin-bottom: 12px; padding: 8px; border: 1px solid #e2e8f0; border-radius: 6px; }
  .photos { display: flex; flex-wrap: wrap; gap: 8px; margin-top: 8px; }
  .photo { margin: 0; width: 140px; }
  .photo img { width: 100%; height: auto; border: 1px solid #e2e8f0; border-radius: 4px; }
  .photo figcaption { font-size: 7pt; color: #64748b; margin-top: 2px; }
  .footer { margin-top: 24px; padding-top: 8px; border-top: 1px solid #e2e8f0; font-size: 8pt; color: #64748b; display: flex; justify-content: space-between; gap: 12px; }
  .generated-by { margin-left: auto; white-space: nowrap; font-size: 7pt; color: #94a3b8; text-align: right; }
  .block { page-break-inside: avoid; }
</style>
</head>
<body>
  <header class="header">
    ${b.company_logo ? `<div class="logo"><img src="${b.company_logo}" alt="Logo"/></div>` : ''}
    <div class="company">
      <h1>${esc(b.company_name)}</h1>
      ${b.company_address ? `<p>${esc(b.company_address).replace(/\n/g, '<br/>')}</p>` : ''}
      <p>${[b.company_phone, b.company_email, b.company_website]
        .filter((s): s is string => Boolean(s))
        .map(esc)
        .join(' · ')}</p>
    </div>
    <div class="cert-meta">
      <strong>Electrical Installation Condition Report</strong>
      <span>BS 7671 — 18th Edition Amd 3</span><br/>
      <span>${esc(input.certificateNumber)}</span>
    </div>
  </header>

  <section class="block">
    <h2>Certificate details</h2>
    <table class="kv">
      ${row('Client', clientLine)}
      ${row('Installation', input.installationLabel ?? '—')}
      ${row('Job number', input.jobNumber ?? '')}
      ${row('Reason for report', inst.reason)}
      ${row('Inspection date', inst.inspectionDate)}
      ${row('Premises type', inst.premisesType)}
      ${row('Overall assessment', inst.overallAssessment)}
      ${row('General condition', inst.generalCondition)}
      ${row('Extent covered', inst.extent)}
      ${row('Reinspection period', inst.reinspectionPeriod)}
    </table>
  </section>

  <section class="block">
    <h2>Observations</h2>
    ${obsHtml}
  </section>

  <section class="block">
    <h2>Supply characteristics</h2>
    <table class="kv">
      ${row('Earthing arrangement', sup.earthing)}
      ${row('Ze (Ω)', sup.ze)}
      ${row('Prospective fault current', sup.ipf)}
      ${row('Nominal voltage U / Uo', `${sup.nominalU} / ${sup.nominalUo}`)}
      ${row('Number of phases', sup.phases)}
    </table>
  </section>

  <section class="block">
    <h2>Inspection schedule</h2>
    ${inspectionRows}
  </section>

  <section class="block">
    <h2>Distribution boards</h2>
    ${boardsHtml || '<p class="muted">No boards</p>'}
  </section>

  ${
    doc.appendix.content.trim()
      ? `<section class="block"><h2>Appendix notes</h2><p style="white-space:pre-wrap">${esc(doc.appendix.content)}</p></section>`
      : ''
  }
  ${appendixPhotos.length ? photosHtml(appendixPhotos, 'Appendix photographs') : ''}

  <section class="block">
    <h2>Declaration</h2>
    <table class="kv">
      ${row('Inspected and tested by', inst.inspectedBy)}
      ${row('Inspector position', inst.inspectedPosition)}
      ${row('Inspected date', inst.inspectedDate)}
      ${row('Authorised for issue by', inst.authorisedBy)}
      ${row('Authorised position', inst.authorisedPosition)}
      ${row('Authorised date', inst.authorisedDate)}
    </table>
  </section>

  ${certificateFooterHtml(b, input.certificateNumber)}
</body>
</html>`;
}

function buildPatCertificatePdfHtml(input: CertificatePdfInput): string {
  const { document: doc, branding: b } = input;
  const pat = doc.pat;
  if (!pat) throw new Error('PAT_DOCUMENT_MISSING');
  const accent = b.accent_color;
  const applianceRows = pat.appliances
    .map((a) => {
      const status = a.status ? a.status[0].toUpperCase() + a.status.slice(1) : '—';
      return `<tr><td>${esc(a.applianceId)}</td><td>${esc(a.brand || 'N/A')}</td><td>${esc(a.description)}</td><td>${esc(a.location)}</td><td>${esc(a.serialNo || 'N/A')}</td><td>${esc(a.retestPeriod)}</td><td class="status">${esc(status)}</td></tr>`;
    })
    .join('');
  const block = (title: string, lines: string[]) => `
    <div class="info-block">
      <h2>${esc(title)}</h2>
      ${lines.filter((line) => line.trim()).map((line) => `<p>${esc(line).replace(/\n/g, '<br/>')}</p>`).join('')}
    </div>`;

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>${esc(input.certificateNumber)} — PAT</title>
<style>
  @page { size: A4; margin: 14mm; }
  * { box-sizing: border-box; }
  body { font-family: system-ui, -apple-system, Segoe UI, sans-serif; font-size: 9pt; color: #0f172a; margin: 0; }
  .header { display: flex; gap: 16px; border-bottom: 3px solid ${accent}; padding-bottom: 12px; margin-bottom: 16px; }
  .logo { width: 72px; height: 72px; flex-shrink: 0; display: flex; align-items: center; justify-content: center; }
  .logo img { max-width: 100%; max-height: 100%; object-fit: contain; }
  .company h1 { margin: 0; font-size: 14pt; color: ${accent}; }
  .company p { margin: 2px 0 0; font-size: 9pt; color: #475569; }
  .cert-meta { margin-left: auto; text-align: right; font-size: 9pt; }
  .cert-meta strong { display: block; font-size: 12pt; color: #0f172a; }
  .grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 8px; margin-bottom: 14px; }
  .info-block { border: 1px solid #e2e8f0; border-radius: 6px; padding: 8px; page-break-inside: avoid; }
  h2 { font-size: 10pt; margin: 0 0 6px; color: #0f172a; }
  p { margin: 2px 0; color: #334155; }
  table { width: 100%; border-collapse: collapse; font-size: 7.5pt; }
  th, td { border: 1px solid #cbd5e1; padding: 3px 4px; text-align: left; vertical-align: top; }
  th { background: #f8fafc; color: #475569; }
  .status { font-weight: 700; }
  .signature { margin-top: 8px; padding-top: 6px; border-top: 1px solid #e2e8f0; }
  .signature img { max-width: 220px; max-height: 70px; object-fit: contain; display: block; }
  .signature small { color: #64748b; }
  .footer { margin-top: 24px; padding-top: 8px; border-top: 1px solid #e2e8f0; font-size: 8pt; color: #64748b; display: flex; justify-content: space-between; gap: 12px; }
  .generated-by { margin-left: auto; white-space: nowrap; font-size: 7pt; color: #94a3b8; text-align: right; }
</style>
</head>
<body>
  <header class="header">
    ${b.company_logo ? `<div class="logo"><img src="${b.company_logo}" alt="Logo"/></div>` : ''}
    <div class="company">
      <h1>${esc(b.company_name)}</h1>
      ${b.company_address ? `<p>${esc(b.company_address).replace(/\n/g, '<br/>')}</p>` : ''}
      <p>${[b.company_phone, b.company_email, b.company_website].filter((s): s is string => Boolean(s)).map(esc).join(' · ')}</p>
    </div>
    <div class="cert-meta">
      <strong>Portable Appliance Test Certificate</strong>
      <span>${esc(input.certificateNumber)}</span>
    </div>
  </header>
  <section class="grid">
    ${block('Registered Business', [pat.registeredBusiness.name, pat.registeredBusiness.address, pat.registeredBusiness.phone])}
    ${block('Job Address', [pat.jobAddress.customerName || input.customerName || '', pat.jobAddress.address || input.installationLabel || '', pat.jobAddress.landlordAgent])}
    ${block('Certificate Information', [
      `Date: ${pat.certificateInfo.date || '—'}`,
      `Number: ${pat.certificateInfo.number || input.certificateNumber}`,
      `Total appliance tested: ${pat.certificateInfo.totalTested || '0'}`,
      `Total appliance passed: ${pat.certificateInfo.totalPassed || '0'}`,
      `Total appliance failed: ${pat.certificateInfo.totalFailed || '0'}`,
    ])}
  </section>
  <section>
    <h2>Appliance details and test results</h2>
    <table>
      <thead><tr><th>ID</th><th>Brand</th><th>Description</th><th>Location</th><th>Serial no</th><th>Retest period</th><th>Status</th></tr></thead>
      <tbody>${applianceRows}</tbody>
    </table>
  </section>
  <section class="grid" style="grid-template-columns: repeat(2, 1fr); margin-top: 14px;">
    ${block('Test equipment used', [pat.testEquipment.make, `Serial no: ${pat.testEquipment.serialNo}`, pat.testEquipment.notes])}
    <div class="info-block">
      <h2>Engineer declaration</h2>
      ${[pat.engineer.name, pat.engineer.notes].filter((line) => line.trim()).map((line) => `<p>${esc(line).replace(/\n/g, '<br/>')}</p>`).join('')}
      ${pat.engineer.signatureDataUrl ? `<div class="signature"><img src="${pat.engineer.signatureDataUrl}" alt="Engineer signature"/><small>Signed${pat.engineer.signedAt ? `: ${esc(new Date(pat.engineer.signedAt).toLocaleString('en-GB'))}` : ''}</small></div>` : ''}
    </div>
  </section>
  ${certificateFooterHtml(b, input.certificateNumber)}
</body>
</html>`;
}

function buildFireAlarmCertificatePdfHtml(input: CertificatePdfInput): string {
  const { document: doc, branding: b } = input;
  const fa = doc.fireAlarm;
  if (!fa) throw new Error('FIRE_ALARM_DOCUMENT_MISSING');
  const accent = b.accent_color;

  const scheduleSections = [...new Set(FIRE_ALARM_INSPECTION_SCHEDULE_ITEMS.map((i) => i.section))]
    .map((sec) => {
      const items = FIRE_ALARM_INSPECTION_SCHEDULE_ITEMS.filter((i) => i.section === sec);
      const rows = items
        .map((item) => {
          const outcome = fa.inspectionSchedule[item.id] ?? '';
          return `<tr><td class="mono">${esc(item.id)}</td><td>${esc(item.label)}</td><td class="outcome">${esc(FIRE_ALARM_OUTCOME_LABELS[outcome] ?? outcome)}</td></tr>`;
        })
        .join('');
      return `<h3>${esc(sec)}. ${esc(FIRE_ALARM_SECTION_LABELS[sec] ?? sec)}</h3><table class="sched"><thead><tr><th>Ref</th><th>Item</th><th>Outcome</th></tr></thead><tbody>${rows}</tbody></table>`;
    })
    .join('');

  const variationsHtml =
    fa.variations.length > 0
      ? `<ul>${fa.variations
          .map(
            (v) =>
              `<li><strong>${esc(v.code || '—')}</strong> ${esc(v.location)}: ${esc(v.details)}</li>`,
          )
          .join('')}</ul>`
      : '<p class="muted">No variations recorded</p>';

  const appendixPhotos = doc.appendix.photos ?? [];

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>${esc(input.certificateNumber)} — Fire Alarm</title>
<style>
  @page { size: A4; margin: 14mm; }
  body { font-family: system-ui, sans-serif; font-size: 9pt; color: #0f172a; margin: 0; }
  .header { border-bottom: 3px solid ${accent}; padding-bottom: 12px; margin-bottom: 16px; }
  .header h1 { margin: 0; font-size: 14pt; color: ${accent}; }
  .header p { margin: 4px 0 0; color: #475569; font-size: 9pt; }
  .block { margin-bottom: 14px; page-break-inside: avoid; }
  h2 { font-size: 11pt; margin: 0 0 8px; border-bottom: 1px solid #e2e8f0; padding-bottom: 4px; }
  h3 { font-size: 10pt; margin: 12px 0 6px; }
  table.kv { width: 100%; border-collapse: collapse; }
  table.kv td { padding: 4px 8px; border-bottom: 1px solid #f1f5f9; vertical-align: top; }
  table.kv .lbl { width: 38%; font-weight: 600; color: #475569; }
  table.sched { width: 100%; border-collapse: collapse; font-size: 7.5pt; margin-bottom: 10px; }
  table.sched th, table.sched td { border: 1px solid #cbd5e1; padding: 3px 5px; }
  table.sched th { background: #f8fafc; }
  .mono { font-family: ui-monospace, monospace; width: 48px; }
  .outcome { text-align: center; font-weight: 700; width: 48px; }
  .muted { color: #94a3b8; font-style: italic; }
  .footer { margin-top: 24px; padding-top: 8px; border-top: 1px solid #e2e8f0; font-size: 8pt; color: #64748b; display: flex; justify-content: space-between; gap: 12px; }
  .generated-by { margin-left: auto; white-space: nowrap; font-size: 7pt; color: #94a3b8; text-align: right; }
</style>
</head>
<body>
  <header class="header">
    <h1>${esc(b.company_name)}</h1>
    <p>Fire Alarm Inspection &amp; Servicing Report · BS 5839-1:2025</p>
    <p><strong>${esc(input.certificateNumber)}</strong>${input.jobNumber ? ` · Job ${esc(input.jobNumber)}` : ''}</p>
    <p>Client: ${esc(input.customerName ?? '—')}${input.installationLabel ? ` · ${esc(input.installationLabel)}` : ''}</p>
  </header>

  <section class="block">
    <h2>Installation</h2>
    <table class="kv">
      ${row('Occupier', fa.installation.occupierName)}
      ${row('Details of system', fa.installation.detailsOfSystem)}
      ${row('Extent covered', fa.installation.extentOfSystem)}
      ${row('Previous service', fa.installation.previousServiceUnknown ? 'Unknown' : fa.installation.previousServiceDate)}
    </table>
  </section>

  <section class="block">
    <h2>Limitations &amp; documentation</h2>
    <table class="kv">
      ${row('Limitations', fa.limitations.limitationsText)}
      ${row('Related documents', fa.limitations.relatedDocuments)}
      ${row('Essential references', fa.limitations.essentialReferenceDocs)}
    </table>
  </section>

  <section class="block">
    <h2>Condition &amp; summary</h2>
    <table class="kv">
      ${row('General condition', fa.condition.generalCondition)}
      ${row('Inspection date', fa.condition.inspectionDate)}
      ${row('Outstanding defects reported', fa.condition.outstandingDefectsReported || '—')}
      ${row('Log book updated', fa.condition.logBookUpdated || '—')}
      ${row('False alarms (12 months)', fa.condition.falseAlarmsNa ? 'N/A' : fa.condition.falseAlarmsCount)}
      ${row('False alarms rate', fa.condition.falseAlarmsEquatesNa ? 'N/A' : fa.condition.falseAlarmsEquates)}
      ${row('Overall assessment', fa.summary.overallAssessment || '—')}
      ${row('Next inspection', fa.summary.nextInspectionDate || fa.summary.nextInspectionPreset || '—')}
    </table>
  </section>

  <section class="block">
    <h2>Declaration</h2>
    <table class="kv">
      ${row('Inspected by', fa.declaration.inspectedBy)}
      ${row('Inspector position', fa.declaration.inspectedPosition)}
      ${row('Inspection date', fa.declaration.inspectionDate)}
      ${row('Authorised by', fa.declaration.authorisedBy)}
      ${row('Authorised position', fa.declaration.authorisedPosition)}
      ${row('Authorised date', fa.declaration.authorisedDate)}
    </table>
  </section>

  <section class="block">
    <h2>Variations</h2>
    ${variationsHtml}
    ${fa.remedialActions.trim() ? `<h3>Remedial actions</h3><p style="white-space:pre-wrap">${esc(fa.remedialActions)}</p>` : ''}
  </section>

  <section class="block">
    <h2>Inspection schedule</h2>
    ${scheduleSections}
  </section>

  ${
    doc.appendix.content.trim()
      ? `<section class="block"><h2>Appendix</h2><p style="white-space:pre-wrap">${esc(doc.appendix.content)}</p></section>`
      : ''
  }
  ${appendixPhotos.length ? photosHtml(appendixPhotos, 'Appendix photographs') : ''}

  ${certificateFooterHtml(b, input.certificateNumber)}
</body>
</html>`;
}

function buildDomesticFireAlarmCertificatePdfHtml(input: CertificatePdfInput): string {
  const { document: doc, branding: b } = input;
  const domestic = doc.domesticFireAlarm;
  if (!domestic) throw new Error('DOMESTIC_FIRE_ALARM_DOCUMENT_MISSING');
  const accent = b.accent_color;

  const checklistHtml = [...new Set(DOMESTIC_FIRE_ALARM_CHECKLIST_ITEMS.map((i) => i.section))]
    .map((sec) => {
      const rows = DOMESTIC_FIRE_ALARM_CHECKLIST_ITEMS.filter((i) => i.section === sec)
        .map((item) => {
          const outcome = domestic.checklist[item.id] ?? '';
          return `<tr><td>${esc(item.label)}</td><td class="outcome">${esc(DOMESTIC_FIRE_ALARM_CHECKLIST_OUTCOME_LABELS[outcome] ?? '-')}</td></tr>`;
        })
        .join('');
      return `<h3>${esc(domesticChecklistSectionLabel(sec))}</h3><table class="sched"><thead><tr><th>Item</th><th>Outcome</th></tr></thead><tbody>${rows}</tbody></table>`;
    })
    .join('');

  const variationsHtml =
    domestic.variations.length > 0
      ? `<ul>${domestic.variations
          .map((v) => `<li><strong>${esc(v.code || '-')}</strong> ${esc(v.location)}: ${esc(v.details)}</li>`)
          .join('')}</ul>`
      : '<p class="muted">No variations recorded</p>';

  const detectorRows =
    domestic.detectors.length > 0
      ? domestic.detectors
          .map(
            (d) =>
              `<tr><td>${esc(d.reference)}</td><td>${esc(d.location)}</td><td>${esc(d.make)}</td><td>${esc(d.model)}</td><td>${esc(d.detectorTypes.join(', '))}</td><td>${esc(d.powerSource)}</td><td>${esc(d.interlink)}</td><td>${esc(d.fitForContinuedService.toUpperCase() || '-')}</td></tr>`,
          )
          .join('')
      : '<tr><td colspan="8" class="muted">No detectors recorded</td></tr>';

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>${esc(input.certificateNumber)} - Domestic Fire Alarm</title>
<style>
  @page { size: A4; margin: 14mm; }
  body { font-family: system-ui, sans-serif; font-size: 9pt; color: #0f172a; margin: 0; }
  .header { border-bottom: 3px solid ${accent}; padding-bottom: 12px; margin-bottom: 16px; }
  .header h1 { margin: 0; font-size: 14pt; color: ${accent}; }
  .header p { margin: 4px 0 0; color: #475569; font-size: 9pt; }
  .block { margin-bottom: 14px; page-break-inside: avoid; }
  h2 { font-size: 11pt; margin: 0 0 8px; border-bottom: 1px solid #e2e8f0; padding-bottom: 4px; }
  h3 { font-size: 10pt; margin: 12px 0 6px; }
  table.kv, table.sched { width: 100%; border-collapse: collapse; }
  table.kv td { padding: 4px 8px; border-bottom: 1px solid #f1f5f9; vertical-align: top; }
  table.kv .lbl { width: 38%; font-weight: 600; color: #475569; }
  table.sched { font-size: 7.5pt; margin-bottom: 10px; }
  table.sched th, table.sched td { border: 1px solid #cbd5e1; padding: 3px 5px; }
  table.sched th { background: #f8fafc; }
  .outcome { text-align: center; font-weight: 700; width: 56px; }
  .muted { color: #94a3b8; font-style: italic; }
  .footer { margin-top: 24px; padding-top: 8px; border-top: 1px solid #e2e8f0; font-size: 8pt; color: #64748b; display: flex; justify-content: space-between; gap: 12px; }
  .generated-by { margin-left: auto; white-space: nowrap; font-size: 7pt; color: #94a3b8; text-align: right; }
</style>
</head>
<body>
  <header class="header">
    <h1>${esc(b.company_name)}</h1>
    <p>Domestic Fire Alarm Inspection &amp; Servicing Report</p>
    <p>Standard: ${esc(DOMESTIC_FIRE_ALARM_STANDARD)} · Revision: ${esc(DOMESTIC_FIRE_ALARM_REVISION)}</p>
    <p><strong>${esc(input.certificateNumber)}</strong>${input.jobNumber ? ` · Job ${esc(input.jobNumber)}` : ''}</p>
    <p>Client: ${esc(input.customerName ?? '-')}${input.installationLabel ? ` · ${esc(input.installationLabel)}` : ''}</p>
  </header>

  <section class="block">
    <h2>Installation details</h2>
    <table class="kv">
      ${row('Occupier', domestic.installation.occupierName)}
      ${row('System grade', domestic.installation.systemGrade)}
      ${row('System category', domestic.installation.systemCategory)}
      ${row('Extent covered', domestic.installation.extentOfSystem)}
      ${row('Limitations', domestic.installation.limitations)}
      ${row('General condition', domestic.installation.generalCondition)}
      ${row('Overall assessment', domestic.summary.overallAssessment)}
      ${row('Next inspection', domestic.summary.nextInspectionDate || domestic.summary.nextInspectionPreset)}
    </table>
  </section>

  <section class="block">
    <h2>Declaration</h2>
    <table class="kv">
      ${row('Inspected by', domestic.declaration.inspectedBy)}
      ${row('Inspector position', domestic.declaration.inspectedPosition)}
      ${row('Inspection date', domestic.declaration.inspectionDate)}
      ${row('Authorised by', domestic.declaration.authorisedBy)}
      ${row('Authorised position', domestic.declaration.authorisedPosition)}
      ${row('Authorised date', domestic.declaration.authorisedDate)}
    </table>
  </section>

  <section class="block"><h2>Variations</h2>${variationsHtml}</section>
  ${domestic.remedialActions.trim() ? `<section class="block"><h2>Remedial actions</h2><p style="white-space:pre-wrap">${esc(domestic.remedialActions)}</p></section>` : ''}
  <section class="block"><h2>Checklist</h2>${checklistHtml}</section>
  <section class="block"><h2>Detectors</h2><table class="sched"><thead><tr><th>Ref</th><th>Location</th><th>Make</th><th>Model</th><th>Type</th><th>Power</th><th>Interlink</th><th>Fit</th></tr></thead><tbody>${detectorRows}</tbody></table></section>
  ${doc.appendix.content.trim() ? `<section class="block"><h2>Appendix</h2><p style="white-space:pre-wrap">${esc(doc.appendix.content)}</p></section>` : ''}
  ${doc.appendix.photos.length ? photosHtml(doc.appendix.photos, 'Appendix photographs') : ''}
  ${certificateFooterHtml(b, input.certificateNumber)}
</body>
</html>`;
}

function domesticChecklistSectionLabel(section: keyof typeof DOMESTIC_FIRE_ALARM_CHECKLIST_SECTION_LABELS): string {
  return DOMESTIC_FIRE_ALARM_CHECKLIST_SECTION_LABELS[section] ?? section;
}
