import type { CompanyBranding } from './companyBranding';
import {
  DOMESTIC_FIRE_ALARM_CHECKLIST_ITEMS,
  DOMESTIC_FIRE_ALARM_CHECKLIST_OUTCOME_LABELS,
  DOMESTIC_FIRE_ALARM_CHECKLIST_SECTION_LABELS,
  DOMESTIC_FIRE_ALARM_REVISION,
  DOMESTIC_FIRE_ALARM_STANDARD,
} from './domesticFireAlarmItems';
import {
  DOMESTIC_FIRE_ALARM_INST_FIXED_TESTS,
  DOMESTIC_FIRE_ALARM_INST_PASS_NA_LABELS,
  DOMESTIC_FIRE_ALARM_INST_TEST_RESULTS_LABELS,
  DOMESTIC_FIRE_ALARM_SYSTEM_IS_LABELS,
} from './domesticFireAlarmInstItems';
import {
  FIRE_ALARM_INSPECTION_SCHEDULE_ITEMS,
  FIRE_ALARM_OUTCOME_LABELS,
  FIRE_ALARM_SECTION_LABELS,
} from './fireAlarmInspectionScheduleItems';
import {
  FIRE_EXTINGUISHER_BLANKET_OUTCOME_LABELS,
  FIRE_EXTINGUISHER_CHECKLIST_ITEMS,
  FIRE_EXTINGUISHER_CHECKLIST_OUTCOME_LABELS,
  FIRE_EXTINGUISHER_PREMISES_LABELS,
  FIRE_EXTINGUISHER_SERVICE_CODE_LABELS,
  FIRE_EXTINGUISHER_STANDARD_LABEL,
  FIRE_EXTINGUISHER_TYPE_LABELS,
} from './fireExtinguisherItems';
import { INSPECTION_SCHEDULE_ITEMS, INSPECTION_SECTION_LABELS } from './inspectionScheduleItems';
import type { ElectricalCertificateDocument, InspectionOutcome } from './types';

export type CertificatePdfInput = {
  certificateNumber: string;
  customerName: string | null;
  installationLabel: string | null;
  jobNumber: string | null;
  document: ElectricalCertificateDocument;
  branding: CompanyBranding;
};

const OUTCOME_LABELS: Record<InspectionOutcome, string> = {
  '': '—',
  pass: '✓',
  c1: 'C1',
  c2: 'C2',
  c3: 'C3',
  fi: 'FI',
  lim: 'LIM',
  nv: 'N/V',
  na: 'N/A',
  x: 'X',
};

function esc(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function row(label: string, value: string): string {
  if (!value.trim()) return '';
  return `<tr><td class="lbl">${esc(label)}</td><td>${esc(value)}</td></tr>`;
}

function photosHtml(photos: { caption: string; dataUrl: string }[], title: string): string {
  if (!photos.length) return '';
  const items = photos
    .map(
      (p) =>
        `<figure class="photo"><img src="${p.dataUrl}" alt="${esc(p.caption || 'Photo')}"/><figcaption>${esc(p.caption || '')}</figcaption></figure>`,
    )
    .join('');
  return `<section class="block"><h2>${esc(title)}</h2><div class="photos">${items}</div></section>`;
}

function certificateFooterHtml(branding: CompanyBranding, certificateNumber: string): string {
  const primary = branding.footer_text?.trim()
    || [branding.company_name.trim(), certificateNumber].filter(Boolean).join(' · ')
    || certificateNumber;
  return `<div class="footer"><span>${esc(primary)}</span><span class="generated-by">Generated by WorkPilot</span></div>`;
}

function certificatePdfStyles(accent: string, accentEnd: string, fontSize = '9pt'): string {
  return `
  @page { size: A4; margin: 12mm; }
  * { box-sizing: border-box; }
  body { font-family: Arial, Helvetica, sans-serif; font-size: ${fontSize}; line-height: 1.38; color: #111827; margin: 0; background: #fff; }
  .header { display: flex; gap: 16px; align-items: stretch; margin-bottom: 18px; border: 1px solid #dbe3ea; border-top: 5px solid ${accent}; border-radius: 12px; overflow: hidden; background: linear-gradient(135deg, #ffffff 0%, #f8fafc 100%); }
  .logo { width: 78px; min-height: 78px; flex-shrink: 0; display: flex; align-items: center; justify-content: center; padding: 10px; background: #fff; border-right: 1px solid #e5edf3; }
  .logo img { max-width: 100%; max-height: 100%; object-fit: contain; }
  .company { flex: 1; padding: 12px 10px; }
  .company h1 { margin: 0; font-size: 15pt; letter-spacing: -0.01em; color: ${accent}; }
  .company p { margin: 3px 0 0; font-size: 8.5pt; color: #4b5563; }
  .cert-meta { width: 210px; padding: 12px; color: #fff; background: linear-gradient(135deg, ${accent}, ${accentEnd}); }
  .cert-meta strong { display: block; margin-bottom: 6px; font-size: 11pt; line-height: 1.2; }
  .cert-meta span { display: block; margin-top: 3px; font-size: 8pt; opacity: .95; }
  .block, .info-block, .board { margin-bottom: 12px; padding: 10px 11px; border: 1px solid #dbe3ea; border-radius: 10px; background: #fff; page-break-inside: avoid; box-shadow: 0 1px 0 rgba(15, 23, 42, 0.04); }
  h2 { margin: -10px -11px 9px; padding: 8px 11px; border-bottom: 1px solid #dbe3ea; border-radius: 10px 10px 0 0; background: #f3f7fa; color: #111827; font-size: 10.5pt; letter-spacing: .01em; }
  h3 { margin: 10px 0 6px; color: #334155; font-size: 9.5pt; }
  p { margin: 3px 0; color: #334155; }
  .grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 10px; margin-bottom: 12px; }
  table.kv, table.sched, table { width: 100%; border-collapse: separate; border-spacing: 0; }
  table.kv td { padding: 4px 7px; vertical-align: top; border-bottom: 1px solid #eef2f6; }
  table.kv tr:last-child td { border-bottom: 0; }
  table.kv td.lbl, table.kv .lbl { width: 36%; color: #64748b; font-weight: 700; }
  table.sched, table:not(.kv) { font-size: 7.6pt; border: 1px solid #dbe3ea; border-radius: 8px; overflow: hidden; }
  table.sched th, table.sched td, table:not(.kv) th, table:not(.kv) td { border-right: 1px solid #e2e8f0; border-bottom: 1px solid #e2e8f0; padding: 4px 5px; text-align: left; vertical-align: top; }
  table.sched th:last-child, table.sched td:last-child, table:not(.kv) th:last-child, table:not(.kv) td:last-child { border-right: 0; }
  table.sched tr:last-child td, table:not(.kv) tr:last-child td { border-bottom: 0; }
  table.sched th, table:not(.kv) th { background: #eef6f5; color: #334155; font-weight: 800; }
  .mono { width: 44px; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; color: #64748b; }
  .outcome, .status { text-align: center; font-weight: 800; }
  .muted { color: #94a3b8; font-style: italic; }
  ul { margin: 4px 0 0 18px; padding: 0; }
  li { margin: 3px 0; }
  .photos { display: flex; flex-wrap: wrap; gap: 8px; margin-top: 8px; }
  .photo { margin: 0; width: 140px; }
  .photo img { width: 100%; height: auto; border: 1px solid #dbe3ea; border-radius: 8px; }
  .photo figcaption { margin-top: 3px; font-size: 7pt; color: #64748b; }
  .signature { margin-top: 9px; padding-top: 8px; border-top: 1px solid #e2e8f0; }
  .signature img { max-width: 220px; max-height: 70px; object-fit: contain; display: block; }
  .signature small { color: #64748b; }
  .footer { margin-top: 22px; padding-top: 8px; border-top: 1px solid #dbe3ea; font-size: 7.5pt; color: #64748b; display: flex; justify-content: space-between; gap: 12px; }
  .generated-by { margin-left: auto; white-space: nowrap; font-size: 7pt; color: #94a3b8; text-align: right; }
`;
}

function certificateHeaderHtml(input: CertificatePdfInput, title: string, subtitle?: string): string {
  const b = input.branding;
  const contact = [b.company_phone, b.company_email, b.company_website].filter((s): s is string => Boolean(s)).map(esc).join(' · ');
  return `<header class="header">
    ${b.company_logo ? `<div class="logo"><img src="${b.company_logo}" alt="Logo"/></div>` : ''}
    <div class="company">
      ${b.company_name ? `<h1>${esc(b.company_name)}</h1>` : ''}
      ${b.company_address ? `<p>${esc(b.company_address).replace(/\n/g, '<br/>')}</p>` : ''}
      ${contact ? `<p>${contact}</p>` : ''}
      <p>Client: ${esc(input.customerName ?? '—')}${input.installationLabel ? ` · ${esc(input.installationLabel)}` : ''}</p>
    </div>
    <div class="cert-meta">
      <strong>${esc(title)}</strong>
      ${subtitle ? `<span>${esc(subtitle)}</span>` : ''}
      <span>${esc(input.certificateNumber)}</span>
      ${input.jobNumber ? `<span>Job ${esc(input.jobNumber)}</span>` : ''}
    </div>
  </header>`;
}

export function buildCertificatePdfHtml(input: CertificatePdfInput): string {
  const { document: doc, branding: b } = input;
  if (doc.typeSlug === 'portable_appliance_test') {
    return buildPatCertificatePdfHtml(input);
  }
  if (doc.typeSlug === 'fi_insp_2025') {
    return buildFireAlarmCertificatePdfHtml(input);
  }
  if (doc.typeSlug === 'dfi_insp_2019_a1') {
    return buildDomesticFireAlarmCertificatePdfHtml(input);
  }
  if (doc.typeSlug === 'dfi_inst_2019_a1') {
    return buildDomesticFireAlarmInstCertificatePdfHtml(input);
  }
  if (doc.typeSlug === 'fi_extinsp_5306') {
    return buildFireExtinguisherCertificatePdfHtml(input);
  }
  const inst = doc.installation;
  const sup = doc.supply;
  const accent = b.accent_color;
  const accentEnd = b.accent_end_color;

  const clientLine = inst.hideClientOnReport
    ? 'Client withheld on report'
    : esc(input.customerName ?? '—');

  const inspectionRows = [...new Set(INSPECTION_SCHEDULE_ITEMS.map((i) => i.section))]
    .map((sec) => {
      const items = INSPECTION_SCHEDULE_ITEMS.filter((i) => i.section === sec);
      const rows = items
        .map((item) => {
          const outcome = doc.inspectionSchedule[item.id] ?? '';
          return `<tr><td class="mono">${esc(item.id)}</td><td>${esc(item.label)}</td><td class="outcome">${esc(OUTCOME_LABELS[outcome] ?? outcome)}</td></tr>`;
        })
        .join('');
      return `<h3>${esc(sec)}. ${esc(INSPECTION_SECTION_LABELS[sec] ?? sec)}</h3><table class="sched"><thead><tr><th>Ref</th><th>Item</th><th>Outcome</th></tr></thead><tbody>${rows}</tbody></table>`;
    })
    .join('');

  const obsHtml =
    doc.observations.items.length > 0
      ? `<ul>${doc.observations.items
          .map(
            (o) =>
              `<li><strong>${esc(o.code.toUpperCase())}</strong> ${esc(o.location)}: ${esc(o.details)}</li>`,
          )
          .join('')}</ul>`
      : '<p class="muted">None recorded</p>';

  const boardsHtml = doc.boards
    .map((board) => {
      const boardPhotos =
        board.photos?.length > 0
          ? `<div class="photos">${board.photos
              .map(
                (p) =>
                  `<figure class="photo"><img src="${p.dataUrl}" alt=""/><figcaption>${esc(p.caption)}</figcaption></figure>`,
              )
              .join('')}</div>`
          : '';
      return `<div class="board"><h3>${esc(board.name)}</h3>
        <p class="muted">${board.circuits.length} circuits · ${board.status === 'done' ? 'Complete' : 'In progress'}${board.zsAtDb ? ` · Zdb ${esc(board.zsAtDb)} Ω` : ''}</p>
        ${boardPhotos}
      </div>`;
    })
    .join('');

  const appendixPhotos = doc.appendix.photos ?? [];

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>${esc(input.certificateNumber)} — EICR</title>
<style>
${certificatePdfStyles(accent, accentEnd, '9pt')}
</style>
</head>
<body>
  ${certificateHeaderHtml(input, 'Electrical Installation Condition Report', 'BS 7671 - 18th Edition Amd 3')}

  <section class="block">
    <h2>Certificate details</h2>
    <table class="kv">
      ${row('Client', clientLine)}
      ${row('Installation', input.installationLabel ?? '—')}
      ${row('Job number', input.jobNumber ?? '')}
      ${row('Reason for report', inst.reason)}
      ${row('Inspection date', inst.inspectionDate)}
      ${row('Premises type', inst.premisesType)}
      ${row('Overall assessment', inst.overallAssessment)}
      ${row('General condition', inst.generalCondition)}
      ${row('Extent covered', inst.extent)}
      ${row('Reinspection period', inst.reinspectionPeriod)}
    </table>
  </section>

  <section class="block">
    <h2>Observations</h2>
    ${obsHtml}
  </section>

  <section class="block">
    <h2>Supply characteristics</h2>
    <table class="kv">
      ${row('Earthing arrangement', sup.earthing)}
      ${row('Ze (Ω)', sup.ze)}
      ${row('Prospective fault current', sup.ipf)}
      ${row('Nominal voltage U / Uo', `${sup.nominalU} / ${sup.nominalUo}`)}
      ${row('Number of phases', sup.phases)}
    </table>
  </section>

  <section class="block">
    <h2>Inspection schedule</h2>
    ${inspectionRows}
  </section>

  <section class="block">
    <h2>Distribution boards</h2>
    ${boardsHtml || '<p class="muted">No boards</p>'}
  </section>

  ${
    doc.appendix.content.trim()
      ? `<section class="block"><h2>Appendix notes</h2><p style="white-space:pre-wrap">${esc(doc.appendix.content)}</p></section>`
      : ''
  }
  ${appendixPhotos.length ? photosHtml(appendixPhotos, 'Appendix photographs') : ''}

  <section class="block">
    <h2>Declaration</h2>
    <table class="kv">
      ${row('Inspected and tested by', inst.inspectedBy)}
      ${row('Inspector position', inst.inspectedPosition)}
      ${row('Inspected date', inst.inspectedDate)}
      ${row('Authorised for issue by', inst.authorisedBy)}
      ${row('Authorised position', inst.authorisedPosition)}
      ${row('Authorised date', inst.authorisedDate)}
    </table>
  </section>

  ${certificateFooterHtml(b, input.certificateNumber)}
</body>
</html>`;
}

function buildPatCertificatePdfHtml(input: CertificatePdfInput): string {
  const { document: doc, branding: b } = input;
  const pat = doc.pat;
  if (!pat) throw new Error('PAT_DOCUMENT_MISSING');
  const accent = b.accent_color;
  const accentEnd = b.accent_end_color;
  const applianceRows = pat.appliances
    .map((a) => {
      const status = a.status ? a.status[0].toUpperCase() + a.status.slice(1) : '—';
      return `<tr><td>${esc(a.applianceId)}</td><td>${esc(a.brand || 'N/A')}</td><td>${esc(a.description)}</td><td>${esc(a.location)}</td><td>${esc(a.serialNo || 'N/A')}</td><td>${esc(a.retestPeriod)}</td><td class="status">${esc(status)}</td></tr>`;
    })
    .join('');
  const block = (title: string, lines: string[]) => `
    <div class="info-block">
      <h2>${esc(title)}</h2>
      ${lines.filter((line) => line.trim()).map((line) => `<p>${esc(line).replace(/\n/g, '<br/>')}</p>`).join('')}
    </div>`;

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>${esc(input.certificateNumber)} — PAT</title>
<style>
${certificatePdfStyles(accent, accentEnd, '8.8pt')}
</style>
</head>
<body>
  ${certificateHeaderHtml(input, 'Portable Appliance Test Certificate')}
  <section class="grid">
    ${block('Registered Business', [pat.registeredBusiness.name, pat.registeredBusiness.address, pat.registeredBusiness.phone])}
    ${block('Job Address', [pat.jobAddress.customerName || input.customerName || '', pat.jobAddress.address || input.installationLabel || '', pat.jobAddress.landlordAgent])}
    ${block('Certificate Information', [
      `Date: ${pat.certificateInfo.date || '—'}`,
      `Number: ${pat.certificateInfo.number || input.certificateNumber}`,
      `Total appliance tested: ${pat.certificateInfo.totalTested || '0'}`,
      `Total appliance passed: ${pat.certificateInfo.totalPassed || '0'}`,
      `Total appliance failed: ${pat.certificateInfo.totalFailed || '0'}`,
    ])}
  </section>
  <section>
    <h2>Appliance details and test results</h2>
    <table>
      <thead><tr><th>ID</th><th>Brand</th><th>Description</th><th>Location</th><th>Serial no</th><th>Retest period</th><th>Status</th></tr></thead>
      <tbody>${applianceRows}</tbody>
    </table>
  </section>
  <section class="grid" style="grid-template-columns: repeat(2, 1fr); margin-top: 14px;">
    ${block('Test equipment used', [pat.testEquipment.make, `Serial no: ${pat.testEquipment.serialNo}`, pat.testEquipment.notes])}
    <div class="info-block">
      <h2>Engineer declaration</h2>
      ${[pat.engineer.name, pat.engineer.notes].filter((line) => line.trim()).map((line) => `<p>${esc(line).replace(/\n/g, '<br/>')}</p>`).join('')}
      ${pat.engineer.signatureDataUrl ? `<div class="signature"><img src="${pat.engineer.signatureDataUrl}" alt="Engineer signature"/><small>Signed${pat.engineer.signedAt ? `: ${esc(pat.engineer.signedAt.slice(0, 10))}` : ''}</small></div>` : ''}
    </div>
  </section>
  ${certificateFooterHtml(b, input.certificateNumber)}
</body>
</html>`;
}

function buildFireAlarmCertificatePdfHtml(input: CertificatePdfInput): string {
  const { document: doc, branding: b } = input;
  const fa = doc.fireAlarm;
  if (!fa) throw new Error('FIRE_ALARM_DOCUMENT_MISSING');
  const accent = b.accent_color;
  const accentEnd = b.accent_end_color;

  const scheduleSections = [...new Set(FIRE_ALARM_INSPECTION_SCHEDULE_ITEMS.map((i) => i.section))]
    .map((sec) => {
      const items = FIRE_ALARM_INSPECTION_SCHEDULE_ITEMS.filter((i) => i.section === sec);
      const rows = items
        .map((item) => {
          const outcome = fa.inspectionSchedule[item.id] ?? '';
          return `<tr><td class="mono">${esc(item.id)}</td><td>${esc(item.label)}</td><td class="outcome">${esc(FIRE_ALARM_OUTCOME_LABELS[outcome] ?? outcome)}</td></tr>`;
        })
        .join('');
      return `<h3>${esc(sec)}. ${esc(FIRE_ALARM_SECTION_LABELS[sec] ?? sec)}</h3><table class="sched"><thead><tr><th>Ref</th><th>Item</th><th>Outcome</th></tr></thead><tbody>${rows}</tbody></table>`;
    })
    .join('');

  const variationsHtml =
    fa.variations.length > 0
      ? `<ul>${fa.variations
          .map(
            (v) =>
              `<li><strong>${esc(v.code || '—')}</strong> ${esc(v.location)}: ${esc(v.details)}</li>`,
          )
          .join('')}</ul>`
      : '<p class="muted">No variations recorded</p>';

  const appendixPhotos = doc.appendix.photos ?? [];

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>${esc(input.certificateNumber)} — Fire Alarm</title>
<style>
${certificatePdfStyles(accent, accentEnd, '8.8pt')}
</style>
</head>
<body>
  ${certificateHeaderHtml(input, 'Fire Alarm Inspection & Servicing Report', 'BS 5839-1:2025')}

  <section class="block">
    <h2>Installation</h2>
    <table class="kv">
      ${row('Occupier', fa.installation.occupierName)}
      ${row('Details of system', fa.installation.detailsOfSystem)}
      ${row('Extent covered', fa.installation.extentOfSystem)}
      ${row('Previous service', fa.installation.previousServiceUnknown ? 'Unknown' : fa.installation.previousServiceDate)}
    </table>
  </section>

  <section class="block">
    <h2>Limitations &amp; documentation</h2>
    <table class="kv">
      ${row('Limitations', fa.limitations.limitationsText)}
      ${row('Related documents', fa.limitations.relatedDocuments)}
      ${row('Essential references', fa.limitations.essentialReferenceDocs)}
    </table>
  </section>

  <section class="block">
    <h2>Condition &amp; summary</h2>
    <table class="kv">
      ${row('General condition', fa.condition.generalCondition)}
      ${row('Inspection date', fa.condition.inspectionDate)}
      ${row('Outstanding defects reported', fa.condition.outstandingDefectsReported || '—')}
      ${row('Log book updated', fa.condition.logBookUpdated || '—')}
      ${row('False alarms (12 months)', fa.condition.falseAlarmsNa ? 'N/A' : fa.condition.falseAlarmsCount)}
      ${row('False alarms rate', fa.condition.falseAlarmsEquatesNa ? 'N/A' : fa.condition.falseAlarmsEquates)}
      ${row('Overall assessment', fa.summary.overallAssessment || '—')}
      ${row('Next inspection', fa.summary.nextInspectionDate || fa.summary.nextInspectionPreset || '—')}
    </table>
  </section>

  <section class="block">
    <h2>Declaration</h2>
    <table class="kv">
      ${row('Inspected by', fa.declaration.inspectedBy)}
      ${row('Inspector position', fa.declaration.inspectedPosition)}
      ${row('Inspection date', fa.declaration.inspectionDate)}
      ${row('Authorised by', fa.declaration.authorisedBy)}
      ${row('Authorised position', fa.declaration.authorisedPosition)}
      ${row('Authorised date', fa.declaration.authorisedDate)}
    </table>
  </section>

  <section class="block">
    <h2>Variations</h2>
    ${variationsHtml}
    ${fa.remedialActions.trim() ? `<h3>Remedial actions</h3><p style="white-space:pre-wrap">${esc(fa.remedialActions)}</p>` : ''}
  </section>

  <section class="block">
    <h2>Inspection schedule</h2>
    ${scheduleSections}
  </section>

  ${
    doc.appendix.content.trim()
      ? `<section class="block"><h2>Appendix</h2><p style="white-space:pre-wrap">${esc(doc.appendix.content)}</p></section>`
      : ''
  }
  ${appendixPhotos.length ? photosHtml(appendixPhotos, 'Appendix photographs') : ''}

  ${certificateFooterHtml(b, input.certificateNumber)}
</body>
</html>`;
}

function buildDomesticFireAlarmCertificatePdfHtml(input: CertificatePdfInput): string {
  const { document: doc, branding: b } = input;
  const domestic = doc.domesticFireAlarm;
  if (!domestic) throw new Error('DOMESTIC_FIRE_ALARM_DOCUMENT_MISSING');
  const accent = b.accent_color;
  const accentEnd = b.accent_end_color;

  const checklistHtml = [...new Set(DOMESTIC_FIRE_ALARM_CHECKLIST_ITEMS.map((i) => i.section))]
    .map((sec) => {
      const rows = DOMESTIC_FIRE_ALARM_CHECKLIST_ITEMS.filter((i) => i.section === sec)
        .map((item) => {
          const outcome = domestic.checklist[item.id] ?? '';
          return `<tr><td>${esc(item.label)}</td><td class="outcome">${esc(DOMESTIC_FIRE_ALARM_CHECKLIST_OUTCOME_LABELS[outcome] ?? '-')}</td></tr>`;
        })
        .join('');
      return `<h3>${esc(domesticChecklistSectionLabel(sec))}</h3><table class="sched"><thead><tr><th>Item</th><th>Outcome</th></tr></thead><tbody>${rows}</tbody></table>`;
    })
    .join('');

  const variationsHtml =
    domestic.variations.length > 0
      ? `<ul>${domestic.variations
          .map((v) => `<li><strong>${esc(v.code || '-')}</strong> ${esc(v.location)}: ${esc(v.details)}</li>`)
          .join('')}</ul>`
      : '<p class="muted">No variations recorded</p>';

  const detectorRows = domestic.detectors
    .map(
      (d) =>
        `<tr><td>${esc(d.reference)}</td><td>${esc(d.location)}</td><td>${esc(d.make)}</td><td>${esc(d.model)}</td><td>${esc(d.detectorTypes.join(', '))}</td><td>${esc(d.powerSource)}</td><td>${esc(d.interlink)}</td><td>${esc(d.fitForContinuedService.toUpperCase() || '-')}</td></tr>`,
    )
    .join('');

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>${esc(input.certificateNumber)} - Domestic Fire Alarm</title>
<style>
${certificatePdfStyles(accent, accentEnd, '8.8pt')}
</style>
</head>
<body>
  ${certificateHeaderHtml(input, 'Domestic Fire Alarm Inspection & Servicing Report', `Standard: ${DOMESTIC_FIRE_ALARM_STANDARD} · Revision: ${DOMESTIC_FIRE_ALARM_REVISION}`)}

  <section class="block">
    <h2>Installation details</h2>
    <table class="kv">
      ${row('Occupier', domestic.installation.occupierName)}
      ${row('System grade', domestic.installation.systemGrade)}
      ${row('System category', domestic.installation.systemCategory)}
      ${row('Extent covered', domestic.installation.extentOfSystem)}
      ${row('Limitations', domestic.installation.limitations)}
      ${row('General condition', domestic.installation.generalCondition)}
      ${row('Overall assessment', domestic.summary.overallAssessment)}
      ${row('Next inspection', domestic.summary.nextInspectionDate || domestic.summary.nextInspectionPreset)}
    </table>
  </section>

  <section class="block">
    <h2>Declaration</h2>
    <table class="kv">
      ${row('Inspected by', domestic.declaration.inspectedBy)}
      ${row('Inspector position', domestic.declaration.inspectedPosition)}
      ${row('Inspection date', domestic.declaration.inspectionDate)}
      ${row('Authorised by', domestic.declaration.authorisedBy)}
      ${row('Authorised position', domestic.declaration.authorisedPosition)}
      ${row('Authorised date', domestic.declaration.authorisedDate)}
    </table>
  </section>

  <section class="block"><h2>Variations</h2>${variationsHtml}</section>
  ${domestic.remedialActions.trim() ? `<section class="block"><h2>Remedial actions</h2><p style="white-space:pre-wrap">${esc(domestic.remedialActions)}</p></section>` : ''}
  <section class="block"><h2>Checklist</h2>${checklistHtml}</section>
  ${detectorRows ? `<section class="block"><h2>Detectors</h2><table class="sched"><thead><tr><th>Ref</th><th>Location</th><th>Make</th><th>Model</th><th>Type</th><th>Power</th><th>Interlink</th><th>Fit</th></tr></thead><tbody>${detectorRows}</tbody></table></section>` : ''}
  ${doc.appendix.content.trim() ? `<section class="block"><h2>Appendix</h2><p style="white-space:pre-wrap">${esc(doc.appendix.content)}</p></section>` : ''}
  ${doc.appendix.photos.length ? photosHtml(doc.appendix.photos, 'Appendix photographs') : ''}
  ${certificateFooterHtml(b, input.certificateNumber)}
</body>
</html>`;
}

function domesticChecklistSectionLabel(section: keyof typeof DOMESTIC_FIRE_ALARM_CHECKLIST_SECTION_LABELS): string {
  return DOMESTIC_FIRE_ALARM_CHECKLIST_SECTION_LABELS[section] ?? section;
}

function buildFireExtinguisherCertificatePdfHtml(input: CertificatePdfInput): string {
  const { document: doc, branding: b } = input;
  const fire = doc.fireExtinguisher;
  if (!fire) throw new Error('FIRE_EXTINGUISHER_DOCUMENT_MISSING');
  const accent = b.accent_color;
  const accentEnd = b.accent_end_color;
  const checklistOutcome = (value: string) => FIRE_EXTINGUISHER_CHECKLIST_OUTCOME_LABELS[value] ?? '—';
  const blanketOutcome = (value: string) => FIRE_EXTINGUISHER_BLANKET_OUTCOME_LABELS[value] ?? '—';
  const capacity = (item: (typeof fire.extinguishers)[number]) =>
    [item.capacity, item.capacityUnit].filter(Boolean).join(' ') || '—';

  const extinguisherRows = fire.extinguishers
    .map(
      (item) =>
        `<tr><td>${esc(item.reference)}</td><td>${esc(item.location)}</td><td>${esc(FIRE_EXTINGUISHER_SERVICE_CODE_LABELS[item.serviceCode] ?? item.serviceCode)}</td><td>${esc(item.make)}</td><td>${esc(FIRE_EXTINGUISHER_TYPE_LABELS[item.extinguisherType] ?? item.extinguisherType)}</td><td>${esc(capacity(item))}</td><td>${esc(item.measuredWeight)}</td><td>${esc(item.nextDischargeDate)}</td><td>${esc(item.endOfLifeDate)}</td><td>${esc(item.notes)}</td></tr>`,
    )
    .join('');

  const blanketRows = fire.blankets
    .map(
      (item) =>
        `<tr><td>${esc(item.reference)}</td><td>${esc(item.location)}</td><td>${esc(item.make)}</td><td>${esc(item.installationDateUnknown ? 'Unknown' : item.installationDate)}</td><td>${esc(item.expiryDate)}</td><td class="outcome">${esc(blanketOutcome(item.outcome))}</td><td>${esc(item.notes)}</td></tr>`,
    )
    .join('');

  const checklistRows = fire.hideChecklistFromReport
    ? ''
    : FIRE_EXTINGUISHER_CHECKLIST_ITEMS.map(
        (item) =>
          `<tr><td>${esc(item.label)}</td><td class="outcome">${esc(checklistOutcome(fire.checklist[item.id] ?? ''))}</td></tr>`,
      ).join('');

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>${esc(input.certificateNumber)} - Fire Extinguisher Inspection</title>
<style>
${certificatePdfStyles(accent, accentEnd, '8.5pt')}
</style>
</head>
<body>
  ${certificateHeaderHtml(input, 'Fire Extinguisher Inspection Certificate', FIRE_EXTINGUISHER_STANDARD_LABEL)}

  <section class="block">
    <h2>Installation details</h2>
    <table class="kv">
      ${row('Occupier', fire.installation.occupierName)}
      ${row('Occupier type', fire.installation.occupierType)}
      ${row('Description of premises', FIRE_EXTINGUISHER_PREMISES_LABELS[fire.installation.premisesType] ?? fire.installation.premisesType)}
      ${row('Next inspection', fire.installation.nextInspectionDate)}
    </table>
  </section>

  <section class="block">
    <h2>Declaration</h2>
    <table class="kv">
      ${row('Inspected and serviced by', fire.declaration.inspectedBy)}
      ${row('Inspector position', fire.declaration.inspectedPosition)}
      ${row('Inspected date', fire.declaration.inspectedDate)}
      ${row('Authorised for issue by', fire.declaration.authorisedBy)}
      ${row('Authorised position', fire.declaration.authorisedPosition)}
      ${row('Authorised date', fire.declaration.authorisedDate)}
    </table>
  </section>

  ${extinguisherRows ? `<section class="block"><h2>Fire extinguishers</h2><table class="sched"><thead><tr><th>Ref</th><th>Location</th><th>Service</th><th>Make</th><th>Type</th><th>Capacity</th><th>Weight</th><th>Next discharge</th><th>End of life</th><th>Notes</th></tr></thead><tbody>${extinguisherRows}</tbody></table></section>` : ''}
  ${blanketRows ? `<section class="block"><h2>Fire blankets</h2><table class="sched"><thead><tr><th>Ref</th><th>Location</th><th>Make</th><th>Installed</th><th>Expiry</th><th>Outcome</th><th>Notes</th></tr></thead><tbody>${blanketRows}</tbody></table></section>` : ''}
  ${checklistRows ? `<section class="block"><h2>Checklist</h2><table class="sched"><thead><tr><th>Item</th><th>Outcome</th></tr></thead><tbody>${checklistRows}</tbody></table></section>` : ''}
  ${fire.remedialActions.trim() ? `<section class="block"><h2>Remedial actions</h2><p style="white-space:pre-wrap">${esc(fire.remedialActions)}</p></section>` : ''}
  ${doc.appendix.content.trim() ? `<section class="block"><h2>Appendix</h2><p style="white-space:pre-wrap">${esc(doc.appendix.content)}</p></section>` : ''}
  ${doc.appendix.photos.length ? photosHtml(doc.appendix.photos, 'Appendix photographs') : ''}
  ${certificateFooterHtml(b, input.certificateNumber)}
</body>
</html>`;
}

function buildDomesticFireAlarmInstCertificatePdfHtml(input: CertificatePdfInput): string {
  const { document: doc, branding: b } = input;
  const inst = doc.domesticFireAlarmInst;
  if (!inst) throw new Error('DOMESTIC_FIRE_ALARM_INST_DOCUMENT_MISSING');
  const accent = b.accent_color;
  const accentEnd = b.accent_end_color;
  const passLabel = (v: string) => DOMESTIC_FIRE_ALARM_INST_PASS_NA_LABELS[v] ?? '—';

  const fixedTestRows = DOMESTIC_FIRE_ALARM_INST_FIXED_TESTS.map(
    (item) =>
      `<tr><td>${esc(item.label)}</td><td class="outcome">${esc(passLabel(String(inst.testSchedule[item.id as keyof typeof inst.testSchedule] ?? '')))}</td></tr>`,
  ).join('');

  const additionalRows = inst.testSchedule.additionalTests
    .map(
      (t) =>
        `<tr><td>${esc(t.description)}</td><td class="outcome">${esc(passLabel(t.outcome))}</td></tr>`,
    )
    .join('');

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>${esc(input.certificateNumber)} - Domestic Fire Alarm Installation</title>
<style>
${certificatePdfStyles(accent, accentEnd, '8.8pt')}
</style>
</head>
<body>
  ${certificateHeaderHtml(input, 'Domestic Fire Alarm Installation Certificate', `Standard: ${DOMESTIC_FIRE_ALARM_STANDARD} · Revision: ${DOMESTIC_FIRE_ALARM_REVISION}`)}

  <section class="block">
    <h2>Installation details</h2>
    <table class="kv">
      ${row('Occupier', inst.installation.occupierName)}
      ${row('System is', DOMESTIC_FIRE_ALARM_SYSTEM_IS_LABELS[inst.installation.systemIs] ?? inst.installation.systemIs)}
      ${row('System grade', inst.installation.systemGrade)}
      ${row('System category', inst.installation.systemCategory)}
      ${row('Related reference documents', inst.documentation.relatedReferenceDocuments)}
      ${row('Extent covered', inst.extent.extentOfSystem)}
      ${row('Specification', inst.specification.specificationText)}
      ${row('Variations from specification', inst.variationsFromSpec.variationsText)}
    </table>
  </section>

  <section class="block">
    <h2>Declaration</h2>
    <table class="kv">
      ${row('Installed by', inst.declaration.installedBy)}
      ${row('Installer position', inst.declaration.installedPosition)}
      ${row('Installation date', inst.declaration.installedDate)}
      ${row('Authorised by', inst.declaration.authorisedBy)}
      ${row('Authorised position', inst.declaration.authorisedPosition)}
      ${row('Authorised date', inst.declaration.authorisedDate)}
    </table>
  </section>

  <section class="block">
    <h2>Test schedule</h2>
    <table class="kv">
      ${row('Wiring tested (BS 5839-1 Clause 38)', passLabel(inst.testSchedule.wiringTested))}
      ${row('Test results recorded', DOMESTIC_FIRE_ALARM_INST_TEST_RESULTS_LABELS[inst.testSchedule.testResultsRecorded] ?? '—')}
    </table>
    <h3>Insulation, supply and manufacturer tests</h3>
    <table class="sched"><thead><tr><th>Test</th><th>Outcome</th></tr></thead><tbody>${fixedTestRows}</tbody></table>
    ${additionalRows ? `<h3>Additional tests</h3><table class="sched"><thead><tr><th>Test</th><th>Outcome</th></tr></thead><tbody>${additionalRows}</tbody></table>` : ''}
  </section>

  ${doc.appendix.content.trim() ? `<section class="block"><h2>Appendix</h2><p style="white-space:pre-wrap">${esc(doc.appendix.content)}</p></section>` : ''}
  ${doc.appendix.photos.length ? photosHtml(doc.appendix.photos, 'Appendix photographs') : ''}
  ${certificateFooterHtml(b, input.certificateNumber)}
</body>
</html>`;
}
