'use client';

import type { ElectricalCertificate, InspectionOutcome } from '@/lib/electricalCertificates/types';
import type { CompanyBranding } from '@/lib/electricalCertificates/companyBranding';
import {
  DOMESTIC_FIRE_ALARM_CHECKLIST_ITEMS,
  DOMESTIC_FIRE_ALARM_CHECKLIST_OUTCOME_LABELS,
  DOMESTIC_FIRE_ALARM_CHECKLIST_SECTION_LABELS,
  DOMESTIC_FIRE_ALARM_REVISION,
  DOMESTIC_FIRE_ALARM_STANDARD,
} from '@/lib/electricalCertificates/domesticFireAlarmItems';
import {
  FIRE_ALARM_INSPECTION_SCHEDULE_ITEMS,
  FIRE_ALARM_OUTCOME_LABELS,
  FIRE_ALARM_SECTION_LABELS,
} from '@/lib/electricalCertificates/fireAlarmInspectionScheduleItems';
import {
  INSPECTION_SCHEDULE_ITEMS,
  INSPECTION_SECTION_LABELS,
} from '@/lib/electricalCertificates/inspectionScheduleItems';
import { CertificateBrandedHeader } from './CertificateBrandedHeader';

const OUTCOME_LABELS: Record<InspectionOutcome, string> = {
  '': '—',
  pass: '✓',
  c1: 'C1',
  c2: 'C2',
  c3: 'C3',
  fi: 'FI',
  lim: 'LIM',
  nv: 'N/V',
  na: 'N/A',
  x: 'X',
};

function CertificateFooter({ branding, certificateNumber }: { branding: CompanyBranding; certificateNumber: string }) {
  const primary = branding.footer_text?.trim()
    || [branding.company_name.trim(), certificateNumber].filter(Boolean).join(' · ')
    || certificateNumber;
  return (
    <footer className="mt-8 flex items-center justify-between gap-3 border-t border-slate-200 pt-3 text-xs text-slate-500">
      <span>{primary}</span>
      <span className="ml-auto whitespace-nowrap text-[10px] text-slate-400">Generated by WorkPilot</span>
    </footer>
  );
}

export function CertificatePrintTemplate({
  certificate,
  branding,
}: {
  certificate: ElectricalCertificate;
  branding: CompanyBranding;
}) {
  const doc = certificate.document;
  if (doc.typeSlug === 'portable_appliance_test') {
    return <PatPrintTemplate certificate={certificate} branding={branding} />;
  }
  if (doc.typeSlug === 'fi_insp_2025') {
    return <FireAlarmPrintTemplate certificate={certificate} branding={branding} />;
  }
  if (doc.typeSlug === 'dfi_insp_2019_a1') {
    return <DomesticFireAlarmPrintTemplate certificate={certificate} branding={branding} />;
  }
  const inst = doc.installation;
  const sup = doc.supply;
  const sections = [...new Set(INSPECTION_SCHEDULE_ITEMS.map((i) => i.section))];

  return (
    <div className="mx-auto max-w-[210mm] bg-white p-8 text-sm text-black print:p-6">
      <CertificateBrandedHeader
        branding={branding}
        certificateNumber={certificate.certificate_number}
      />

      <section className="mb-6">
        <h2 className="mb-2 border-b border-slate-300 font-bold">Certificate details</h2>
        <table className="w-full text-sm">
          <tbody>
            <PrintRow label="Client" value={inst.hideClientOnReport ? 'Withheld' : (certificate.customer_full_name ?? '—')} />
            <PrintRow label="Installation" value={certificate.installation_label ?? '—'} />
            {certificate.job_number && <PrintRow label="Job" value={certificate.job_number} />}
            <PrintRow label="Reason" value={inst.reason} />
            <PrintRow label="Inspection date" value={inst.inspectionDate} />
            <PrintRow label="Premises" value={inst.premisesType} />
            <PrintRow label="Overall assessment" value={inst.overallAssessment} />
            <PrintRow label="General condition" value={inst.generalCondition} />
            <PrintRow label="Extent" value={inst.extent} />
            <PrintRow label="Reinspection" value={inst.reinspectionPeriod} />
          </tbody>
        </table>
      </section>

      {doc.observations.items.length > 0 && (
        <section className="mb-6">
          <h2 className="mb-2 border-b border-slate-300 font-bold">Observations</h2>
          <ul className="list-disc pl-5">
            {doc.observations.items.map((o) => (
              <li key={o.id}>
                <strong>{o.code.toUpperCase()}</strong> {o.location}: {o.details}
              </li>
            ))}
          </ul>
        </section>
      )}

      <section className="mb-6">
        <h2 className="mb-2 border-b border-slate-300 font-bold">Supply characteristics</h2>
        <table className="w-full text-sm">
          <tbody>
            <PrintRow label="Earthing" value={sup.earthing} />
            <PrintRow label="Ze (Ω)" value={sup.ze} />
            <PrintRow label="Ipf" value={sup.ipf} />
            <PrintRow label="Phases" value={sup.phases} />
            <PrintRow label="U / Uo" value={`${sup.nominalU} / ${sup.nominalUo}`} />
          </tbody>
        </table>
      </section>

      <section className="mb-6 break-inside-avoid">
        <h2 className="mb-2 border-b border-slate-300 font-bold">Inspection schedule</h2>
        {sections.map((sec) => {
          const items = INSPECTION_SCHEDULE_ITEMS.filter((i) => i.section === sec);
          return (
            <div key={sec} className="mb-4">
              <h3 className="text-xs font-bold text-slate-700">
                {sec}. {INSPECTION_SECTION_LABELS[sec]}
              </h3>
              <table className="mt-1 w-full border-collapse text-[9px]">
                <thead>
                  <tr className="bg-slate-100">
                    <th className="border border-slate-300 px-1 py-0.5 w-10">Ref</th>
                    <th className="border border-slate-300 px-1 py-0.5 text-left">Item</th>
                    <th className="border border-slate-300 px-1 py-0.5 w-10">Out</th>
                  </tr>
                </thead>
                <tbody>
                  {items.map((item) => (
                    <tr key={item.id}>
                      <td className="border border-slate-200 px-1 font-mono text-slate-500">{item.id}</td>
                      <td className="border border-slate-200 px-1">{item.label}</td>
                      <td className="border border-slate-200 px-1 text-center font-bold">
                        {OUTCOME_LABELS[doc.inspectionSchedule[item.id] ?? '']}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          );
        })}
      </section>

      <section className="mb-6">
        <h2 className="mb-2 border-b border-slate-300 font-bold">Distribution boards</h2>
        {doc.boards.map((b) => (
          <div key={b.id} className="mb-4 rounded border border-slate-200 p-3">
            <p className="font-bold">{b.name}</p>
            <p className="text-xs text-slate-600">
              {b.circuits.length} circuits · {b.status === 'done' ? 'Done' : 'In progress'}
              {b.zsAtDb ? ` · Zdb ${b.zsAtDb} Ω` : ''}
            </p>
            {b.photos.length > 0 && (
              <div className="mt-2 flex flex-wrap gap-2">
                {b.photos.map((p) => (
                  <figure key={p.id} className="w-32">
                    <img src={p.dataUrl} alt="" className="h-24 w-full border object-cover" />
                    {p.caption && <figcaption className="text-[8px] text-slate-500">{p.caption}</figcaption>}
                  </figure>
                ))}
              </div>
            )}
          </div>
        ))}
      </section>

      {doc.appendix.content.trim() && (
        <section className="mb-6">
          <h2 className="mb-2 border-b border-slate-300 font-bold">Appendix</h2>
          <p className="whitespace-pre-wrap">{doc.appendix.content}</p>
        </section>
      )}

      {doc.appendix.photos.length > 0 && (
        <section className="mb-6">
          <h2 className="mb-2 border-b border-slate-300 font-bold">Appendix photographs</h2>
          <div className="flex flex-wrap gap-3">
            {doc.appendix.photos.map((p) => (
              <figure key={p.id} className="w-40">
                <img src={p.dataUrl} alt="" className="h-28 w-full border object-cover" />
                {p.caption && <figcaption className="text-[9px] text-slate-500">{p.caption}</figcaption>}
              </figure>
            ))}
          </div>
        </section>
      )}

      <section className="mb-6">
        <h2 className="mb-2 border-b border-slate-300 font-bold">Declaration</h2>
        <table className="w-full text-sm">
          <tbody>
            <PrintRow label="Inspected and tested by" value={inst.inspectedBy} />
            <PrintRow label="Inspector position" value={inst.inspectedPosition} />
            <PrintRow label="Inspected date" value={inst.inspectedDate} />
            <PrintRow label="Authorised for issue by" value={inst.authorisedBy} />
            <PrintRow label="Authorised position" value={inst.authorisedPosition} />
            <PrintRow label="Authorised date" value={inst.authorisedDate} />
          </tbody>
        </table>
      </section>

      <CertificateFooter branding={branding} certificateNumber={certificate.certificate_number} />
    </div>
  );
}

function FireAlarmPrintTemplate({
  certificate,
  branding,
}: {
  certificate: ElectricalCertificate;
  branding: CompanyBranding;
}) {
  const fa = certificate.document.fireAlarm;
  if (!fa) return null;
  const sections = [...new Set(FIRE_ALARM_INSPECTION_SCHEDULE_ITEMS.map((i) => i.section))];

  return (
    <div className="mx-auto max-w-[210mm] bg-white p-8 text-sm text-black print:p-6">
      <CertificateBrandedHeader
        branding={branding}
        title="Fire Alarm Inspection & Servicing Report"
        subtitle="BS 5839-1:2025"
        certificateNumber={certificate.certificate_number}
      />
      <section className="mb-6">
        <h2 className="mb-2 border-b border-slate-300 font-bold">Client &amp; installation</h2>
        <table className="w-full text-sm">
          <tbody>
            <PrintRow label="Client" value={certificate.customer_full_name ?? '—'} />
            <PrintRow label="Installation" value={certificate.installation_label ?? '—'} />
            <PrintRow label="Occupier" value={fa.installation.occupierName} />
            <PrintRow label="Details of system" value={fa.installation.detailsOfSystem} />
            <PrintRow label="Extent" value={fa.installation.extentOfSystem} />
          </tbody>
        </table>
      </section>
      <section className="mb-6">
        <h2 className="mb-2 border-b border-slate-300 font-bold">Summary</h2>
        <table className="w-full text-sm">
          <tbody>
            <PrintRow label="Overall assessment" value={fa.summary.overallAssessment} />
            <PrintRow label="Next inspection" value={fa.summary.nextInspectionDate || fa.summary.nextInspectionPreset} />
            <PrintRow label="Inspected by" value={fa.declaration.inspectedBy} />
            <PrintRow label="Inspector position" value={fa.declaration.inspectedPosition} />
            <PrintRow label="Inspection date" value={fa.declaration.inspectionDate} />
            <PrintRow label="Authorised by" value={fa.declaration.authorisedBy} />
            <PrintRow label="Authorised position" value={fa.declaration.authorisedPosition} />
            <PrintRow label="Authorised date" value={fa.declaration.authorisedDate} />
          </tbody>
        </table>
      </section>
      {fa.variations.length > 0 && (
        <section className="mb-6">
          <h2 className="mb-2 border-b border-slate-300 font-bold">Variations</h2>
          <ul className="list-disc pl-5 text-sm">
            {fa.variations.map((v) => (
              <li key={v.id}>
                <strong>{v.code || '—'}</strong> {v.location}: {v.details}
              </li>
            ))}
          </ul>
        </section>
      )}
      {sections.map((sec) => {
        const items = FIRE_ALARM_INSPECTION_SCHEDULE_ITEMS.filter((i) => i.section === sec);
        return (
          <section key={sec} className="mb-4 break-inside-avoid">
            <h3 className="mb-1 font-bold">
              {sec}. {FIRE_ALARM_SECTION_LABELS[sec]}
            </h3>
            <table className="w-full border-collapse text-[9px]">
              <thead>
                <tr className="bg-slate-100">
                  <th className="border border-slate-300 px-1 py-0.5">Ref</th>
                  <th className="border border-slate-300 px-1 py-0.5">Item</th>
                  <th className="border border-slate-300 px-1 py-0.5">Outcome</th>
                </tr>
              </thead>
              <tbody>
                {items.map((item) => (
                  <tr key={item.id}>
                    <td className="border border-slate-200 px-1 font-mono">{item.id}</td>
                    <td className="border border-slate-200 px-1">{item.label}</td>
                    <td className="border border-slate-200 px-1 text-center font-bold">
                      {FIRE_ALARM_OUTCOME_LABELS[fa.inspectionSchedule[item.id] ?? '']}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </section>
        );
      })}
      {certificate.document.appendix.content.trim() && (
        <section className="mb-6">
          <h2 className="mb-2 border-b border-slate-300 font-bold">Appendix</h2>
          <p className="whitespace-pre-wrap text-sm">{certificate.document.appendix.content}</p>
        </section>
      )}
      {certificate.document.appendix.photos.length > 0 && (
        <section className="mb-6">
          <h2 className="mb-2 border-b border-slate-300 font-bold">Appendix photographs</h2>
          <div className="grid grid-cols-2 gap-3">
            {certificate.document.appendix.photos.map((p) => (
              <figure key={p.id}>
                <img src={p.dataUrl} alt={p.caption} className="max-h-48 w-full object-contain" />
                {p.caption && <figcaption className="mt-1 text-xs text-slate-600">{p.caption}</figcaption>}
              </figure>
            ))}
          </div>
        </section>
      )}
      <CertificateFooter branding={branding} certificateNumber={certificate.certificate_number} />
    </div>
  );
}

function DomesticFireAlarmPrintTemplate({
  certificate,
  branding,
}: {
  certificate: ElectricalCertificate;
  branding: CompanyBranding;
}) {
  const domestic = certificate.document.domesticFireAlarm;
  if (!domestic) return null;
  const sections = [...new Set(DOMESTIC_FIRE_ALARM_CHECKLIST_ITEMS.map((i) => i.section))];

  return (
    <div className="mx-auto max-w-[210mm] bg-white p-8 text-sm text-black print:p-6">
      <CertificateBrandedHeader
        branding={branding}
        title="Domestic Fire Alarm Inspection and Servicing Report"
        subtitle={`Standard: ${DOMESTIC_FIRE_ALARM_STANDARD} | Revision: ${DOMESTIC_FIRE_ALARM_REVISION}`}
        certificateNumber={certificate.certificate_number}
      />
      <section className="mb-6">
        <h2 className="mb-2 border-b border-slate-300 font-bold">Installation details</h2>
        <table className="w-full text-sm">
          <tbody>
            <PrintRow label="Client" value={certificate.customer_full_name ?? '-'} />
            <PrintRow label="Installation" value={certificate.installation_label ?? '-'} />
            <PrintRow label="Occupier" value={domestic.installation.occupierName} />
            <PrintRow label="System grade" value={domestic.installation.systemGrade} />
            <PrintRow label="System category" value={domestic.installation.systemCategory} />
            <PrintRow label="Overall assessment" value={domestic.summary.overallAssessment} />
            <PrintRow label="Next inspection" value={domestic.summary.nextInspectionDate || domestic.summary.nextInspectionPreset} />
            <PrintRow label="Extent" value={domestic.installation.extentOfSystem} />
            <PrintRow label="Limitations" value={domestic.installation.limitations} />
            <PrintRow label="General condition" value={domestic.installation.generalCondition} />
          </tbody>
        </table>
      </section>
      <section className="mb-6">
        <h2 className="mb-2 border-b border-slate-300 font-bold">Declaration</h2>
        <table className="w-full text-sm">
          <tbody>
            <PrintRow label="Inspected by" value={domestic.declaration.inspectedBy} />
            <PrintRow label="Inspector position" value={domestic.declaration.inspectedPosition} />
            <PrintRow label="Inspection date" value={domestic.declaration.inspectionDate} />
            <PrintRow label="Authorised by" value={domestic.declaration.authorisedBy} />
            <PrintRow label="Authorised position" value={domestic.declaration.authorisedPosition} />
            <PrintRow label="Authorised date" value={domestic.declaration.authorisedDate} />
          </tbody>
        </table>
      </section>
      {domestic.variations.length > 0 && (
        <section className="mb-6">
          <h2 className="mb-2 border-b border-slate-300 font-bold">Variations</h2>
          <ul className="list-disc pl-5 text-sm">
            {domestic.variations.map((v) => (
              <li key={v.id}><strong>{v.code || '-'}</strong> {v.location}: {v.details}</li>
            ))}
          </ul>
        </section>
      )}
      <section className="mb-6 break-inside-avoid">
        <h2 className="mb-2 border-b border-slate-300 font-bold">Checklist</h2>
        {sections.map((sec) => {
          const items = DOMESTIC_FIRE_ALARM_CHECKLIST_ITEMS.filter((i) => i.section === sec);
          return (
            <div key={sec} className="mb-4">
              <h3 className="text-xs font-bold text-slate-700">{DOMESTIC_FIRE_ALARM_CHECKLIST_SECTION_LABELS[sec]}</h3>
              <table className="mt-1 w-full border-collapse text-[9px]">
                <tbody>
                  {items.map((item) => (
                    <tr key={item.id}>
                      <td className="border border-slate-200 px-1">{item.label}</td>
                      <td className="w-14 border border-slate-200 px-1 text-center font-bold">
                        {DOMESTIC_FIRE_ALARM_CHECKLIST_OUTCOME_LABELS[domestic.checklist[item.id] ?? '']}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          );
        })}
      </section>
      <section className="mb-6">
        <h2 className="mb-2 border-b border-slate-300 font-bold">Detectors</h2>
        <table className="w-full border-collapse text-[9px]">
          <thead><tr className="bg-slate-100">{['Ref', 'Location', 'Make', 'Model', 'Type', 'Power', 'Interlink', 'Fit'].map((h) => <th key={h} className="border border-slate-300 px-1 py-0.5 text-left">{h}</th>)}</tr></thead>
          <tbody>
            {domestic.detectors.map((d) => (
              <tr key={d.id}>
                <td className="border border-slate-200 px-1">{d.reference}</td>
                <td className="border border-slate-200 px-1">{d.location}</td>
                <td className="border border-slate-200 px-1">{d.make}</td>
                <td className="border border-slate-200 px-1">{d.model}</td>
                <td className="border border-slate-200 px-1">{d.detectorTypes.join(', ')}</td>
                <td className="border border-slate-200 px-1">{d.powerSource}</td>
                <td className="border border-slate-200 px-1">{d.interlink}</td>
                <td className="border border-slate-200 px-1">{d.fitForContinuedService.toUpperCase()}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </section>
      {certificate.document.appendix.content.trim() && (
        <section className="mb-6">
          <h2 className="mb-2 border-b border-slate-300 font-bold">Appendix</h2>
          <p className="whitespace-pre-wrap text-sm">{certificate.document.appendix.content}</p>
        </section>
      )}
      <CertificateFooter branding={branding} certificateNumber={certificate.certificate_number} />
    </div>
  );
}

function PatPrintTemplate({ certificate, branding }: { certificate: ElectricalCertificate; branding: CompanyBranding }) {
  const pat = certificate.document.pat;
  if (!pat) return null;
  return (
    <div className="mx-auto max-w-[210mm] bg-white p-8 text-sm text-black print:p-6">
      <CertificateBrandedHeader branding={branding} certificateNumber={certificate.certificate_number} />
      <section className="mb-6">
        <h1 className="text-lg font-bold">Portable Appliance Test Certificate</h1>
        <div className="mt-3 grid grid-cols-3 gap-3">
          <InfoBlock title="Registered Business" lines={[pat.registeredBusiness.name, pat.registeredBusiness.address, pat.registeredBusiness.phone]} />
          <InfoBlock title="Job Address" lines={[pat.jobAddress.customerName, pat.jobAddress.address, pat.jobAddress.landlordAgent]} />
          <InfoBlock
            title="Certificate Information"
            lines={[
              `Date: ${pat.certificateInfo.date || '—'}`,
              `Number: ${pat.certificateInfo.number || certificate.certificate_number}`,
              `Total tested: ${pat.certificateInfo.totalTested || '0'}`,
              `Passed: ${pat.certificateInfo.totalPassed || '0'}`,
              `Failed: ${pat.certificateInfo.totalFailed || '0'}`,
            ]}
          />
        </div>
      </section>
      <section className="mb-6">
        <h2 className="mb-2 border-b border-slate-300 font-bold">Appliance details and test results</h2>
        <table className="w-full border-collapse text-[9px]">
          <thead>
            <tr className="bg-slate-100">
              {['ID', 'Brand', 'Description', 'Location', 'Serial no', 'Retest period', 'Status'].map((h) => (
                <th key={h} className="border border-slate-300 px-1 py-0.5 text-left">{h}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {pat.appliances.map((row) => (
              <tr key={row.id}>
                <td className="border border-slate-200 px-1">{row.applianceId}</td>
                <td className="border border-slate-200 px-1">{row.brand || 'N/A'}</td>
                <td className="border border-slate-200 px-1">{row.description}</td>
                <td className="border border-slate-200 px-1">{row.location}</td>
                <td className="border border-slate-200 px-1">{row.serialNo || 'N/A'}</td>
                <td className="border border-slate-200 px-1">{row.retestPeriod}</td>
                <td className="border border-slate-200 px-1 font-bold">{row.status ? row.status[0].toUpperCase() + row.status.slice(1) : '—'}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </section>
      <section className="grid grid-cols-2 gap-4">
        <InfoBlock title="Test equipment used" lines={[pat.testEquipment.make, `Serial no: ${pat.testEquipment.serialNo}`, pat.testEquipment.notes]} />
        <div className="rounded border border-slate-200 p-3">
          <h2 className="mb-2 font-bold">Engineer declaration</h2>
          <div className="space-y-1 whitespace-pre-wrap text-xs">
            {[pat.engineer.name, pat.engineer.notes].filter((line) => line && line.trim()).map((line, idx) => <p key={idx}>{line}</p>)}
            {pat.engineer.signatureDataUrl ? (
              <div className="pt-2">
                <img src={pat.engineer.signatureDataUrl} alt={`${pat.engineer.name} signature`} className="h-16 max-w-full object-contain" />
                <p className="text-slate-500">
                  Signed{pat.engineer.signedAt ? `: ${new Date(pat.engineer.signedAt).toLocaleString()}` : ''}
                </p>
              </div>
            ) : null}
          </div>
        </div>
      </section>
      <CertificateFooter branding={branding} certificateNumber={certificate.certificate_number} />
    </div>
  );
}

function InfoBlock({ title, lines }: { title: string; lines: string[] }) {
  return (
    <div className="rounded border border-slate-200 p-3">
      <h2 className="mb-2 font-bold">{title}</h2>
      <div className="space-y-1 whitespace-pre-wrap text-xs">
        {lines.filter((line) => line && line.trim()).map((line, idx) => <p key={idx}>{line}</p>)}
      </div>
    </div>
  );
}

function PrintRow({ label, value }: { label: string; value: string }) {
  if (!value?.trim()) return null;
  return (
    <tr>
      <td className="w-40 py-0.5 font-semibold text-slate-600">{label}</td>
      <td className="py-0.5">{value}</td>
    </tr>
  );
}
